// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: msg_err_code.proto

package msg_err_code

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgErrCode int32

const (
	// 向服务器发送了错误的数据
	MsgErrCode_no_error MsgErrCode = 0
	// 注册帐号，反序列化 msg_struct.C2SRegisterAccount 失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SRegisterAccount_failed MsgErrCode = 100
	// 注册帐号，帐号非法
	MsgErrCode_register_account_account_id_is_zero MsgErrCode = 101
	// 注册帐号，密码为空
	MsgErrCode_register_account_password_is_empty MsgErrCode = 102
	// 注册帐号，验证码为空
	MsgErrCode_register_account_verification_is_empty MsgErrCode = 103
	// 注册帐号，验证码错误
	MsgErrCode_register_account_verification_is_error MsgErrCode = 104
	// 注册帐号，帐号已存在
	MsgErrCode_register_account_account_is_already_used MsgErrCode = 105
	// 创建账号时, 插入 mysql 出错
	MsgErrCode_register_access_mysql_has_error_when_create_account MsgErrCode = 106
	// 登录帐号，反序列化 msg_struct.C2SLogin 失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SLogin_failed MsgErrCode = 110
	// 登录帐号，帐号非法
	MsgErrCode_login_account_id_is_zero MsgErrCode = 111
	// 登录帐号，帐号或密码错误
	MsgErrCode_login_account_or_pwd_is_wrong MsgErrCode = 112
	// 登录时,读取 mysql 出错
	MsgErrCode_login_access_mysql_has_error_when_load_account MsgErrCode = 113
	// 登录时，帐号已停用
	MsgErrCode_login_account_is_out_of_service MsgErrCode = 114
	// 客户端上传推送、厂商，反序列化msg_struct.C2SDeviceInfo失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SDeviceInfo_has_error MsgErrCode = 120
	// 客户端上传推送、厂商，推送ID为空
	MsgErrCode_device_info_device_info_is_empty MsgErrCode = 121
	// 客户端上传推送、厂商，厂商为空
	MsgErrCode_device_info_device_producter_is_empty MsgErrCode = 122
	// 客户端上传推送、厂商，序列化 msg_struct.DeviceInfo 出错
	MsgErrCode_device_info_device_proto_marshal_msg_struct_DeviceInfo_has_error MsgErrCode = 123
	// 客户端上传推送、厂商，用户-设备号存入redis失败
	MsgErrCode_device_info_account_device_info_save_into_redis_failed MsgErrCode = 124
	// 客户端上传推送、厂商，设备号-用户存入redis失败
	MsgErrCode_device_info_device_info_account_save_into_redis_failed MsgErrCode = 125
	// 客户端上传推送、厂商，存入数据库失败
	MsgErrCode_device_info_save_into_mysql_failed MsgErrCode = 126
	// 客户端设置用户名，反序列化 msg_struct.C2SSetUserName 失败
	MsgErrCode_proto_unmarshal_set_user_name_has_error MsgErrCode = 130
	// 客户端设置用户名，用户名为空
	MsgErrCode_set_user_name_user_name_is_set MsgErrCode = 131
	// 客户端设置用户名，用户名不合法
	MsgErrCode_set_user_name_user_name_is_illegal MsgErrCode = 132
	// 客户端设置用户名，已设置过用户名，不允许修改
	MsgErrCode_set_user_name_user_name_has_been_set MsgErrCode = 133
	// 客户端设置用户名，用户名已存在
	MsgErrCode_set_user_name_user_name_is_exist MsgErrCode = 134
	// 客户端设置用户名，存入 redis 失败
	MsgErrCode_set_user_name_save_into_redis_failed MsgErrCode = 135
	// 客户端设置用户名，存入数据库失败
	MsgErrCode_set_user_name_save_into_mysql_failed MsgErrCode = 136
	// 查找用户，反序列化msg_struct.C2SFindUser失败
	MsgErrCode_proto_unmarshal_find_user_has_error MsgErrCode = 140
	// 查找用户，关键字为空
	MsgErrCode_find_user_key_is_empty MsgErrCode = 141
	// 查找用户，未找到用户
	MsgErrCode_find_user_user_is_not_exist MsgErrCode = 142
	// 设置头像，反序列化 msg_struct.C2SSetHeadPortrait 失败
	MsgErrCode_proto_unmarshal_set_head_portrait_has_error MsgErrCode = 150
	// 设置头像，头像地址为空
	MsgErrCode_set_head_portrait_head_portrait_url_is_empty MsgErrCode = 151
	// 设置头像，存入 redis 出错
	MsgErrCode_set_head_save_head_portrait_url_into_redis_failed MsgErrCode = 152
	// 设置头像，存入数据库出错
	MsgErrCode_set_head_save_head_portrait_url_into_mysql_failed MsgErrCode = 153
	// 修改密码，反序列化 msg_struct.C2SChangePassword 失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SChangePassword_has_error MsgErrCode = 160
	// 修改密码，新密码为空
	MsgErrCode_change_password_new_password_is_empty MsgErrCode = 161
	// 修改密码，存入数据库出错
	MsgErrCode_change_password_save_into_mysql_error MsgErrCode = 162
	// 反序列化 msg_struct.C2SAddFriend 失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SAddFriend_has_error MsgErrCode = 2000
	// 添加好友时，参数错误
	MsgErrCode_add_friend_param_error MsgErrCode = 2001
	// 添加好友：好友申请写入mysql出错
	MsgErrCode_add_friend_mysql_has_error_when_write MsgErrCode = 2002
	// 添加好友：发送者和接收者已经是好友关系
	MsgErrCode_add_friend_sender_and_recevier_are_friends MsgErrCode = 2003
	// 反序列化 msg_struct.C2SAgreeBecomeFriend 失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SAgreeBecomeFriend_has_error MsgErrCode = 2010
	// 同意添加好友：好友通过申请写入mysql出错
	MsgErrCode_agree_become_friend_mysql_has_error_when_write MsgErrCode = 2011
	// 同意添加好友：发送者和接收者已经是好友关系
	MsgErrCode_agree_become_friend_sender_and_receiver_are_friends MsgErrCode = 2012
	// 同意添加好友：在 friend_req 表中没有找到相关记录, 驳回请求
	MsgErrCode_agree_become_friend_mysql_table_friend_req_has_no_record MsgErrCode = 2013
	// 同意添加好友：读取 friend_req 表时发生错误
	MsgErrCode_agree_become_friend_mysql_table_friend_req_has_read_error MsgErrCode = 2014
	// 同意添加好友：不能和自己当好友
	MsgErrCode_agree_become_friend_can_not_be_friend_with_self MsgErrCode = 2015
	// 反序列化 msg_struct.C2SDeleteFriend失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SDeleteFriend_has_error MsgErrCode = 2020
	// 不是好友
	MsgErrCode_delete_friend_is_not_friend MsgErrCode = 2021
	// 服务器内部错误
	MsgErrCode_delete_friend_server_internal_error MsgErrCode = 2022
	// 反序列化 msg_struct.C2SConfirmDeleteFriend失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SConfirmDeleteFriend_has_error MsgErrCode = 2030
	// 不是好友
	MsgErrCode_confirm_friend_is_not_friend MsgErrCode = 2031
	// 服务器内部错误
	MsgErrCode_confirm_friend_server_internal_error MsgErrCode = 2032
	// 发送私聊消息时，反序列化 msg_struct.C2SPrivateChat失败
	MsgErrCode_proto_unmarsharl_msg_struct_C2SPrivateChat_has_error MsgErrCode = 2040
	// 发送私聊消息时，接收者不合法
	MsgErrCode_private_chat_receiver_illegal MsgErrCode = 2041
	// 发送私聊消息时，接受者不是发送者的好友
	MsgErrCode_private_chat_receiver_is_not_friend MsgErrCode = 2042
	// 发送私聊消息时，发送消息类型非法
	MsgErrCode_private_chat_receiver_type_illegal MsgErrCode = 2043
	// 发送私聊消息时，消息类型与对应结构不符（例如，消息类型为voice，但voiceMessage结构体为空）
	MsgErrCode_private_chat_message_type_not_match_message MsgErrCode = 2044
	// 发送私聊消息时，语音url为空
	MsgErrCode_private_chat_voice_url_is_empty MsgErrCode = 2045
	// 发送私聊消息时，语音过长
	MsgErrCode_private_chat_voice_too_long MsgErrCode = 2046
	// 发送私聊消息时，文件url为空
	MsgErrCode_private_chat_file_url_is_empty MsgErrCode = 2047
	// 发送私聊消息时，文件缩略图为空
	MsgErrCode_private_chat_file_thumbnail_url_is_empty MsgErrCode = 2048
	// 发送私聊消息时，视频url为空
	MsgErrCode_private_chat_video_url_is_empty MsgErrCode = 2049
	// 发送私聊消息时，视频缩略图url为空
	MsgErrCode_private_chat_video_thumbnail_url_is_empty MsgErrCode = 2050
	// 发送私聊消息时，cardMessage 为空
	MsgErrCode_private_chat_card_message_is_empty MsgErrCode = 2051
	// 用户撤回私聊消息时，反序列化 msg_struct.C2SWithdrawMessage 失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SWithdrawMessage_has_error MsgErrCode = 2060
	// 用户撤回私聊消息时，私聊消息撤回失败,可能因为已经超过 5 分钟
	MsgErrCode_withDraw_message_private_chat_withdraw_fail MsgErrCode = 2061
	// 用户撤回私聊消息时，撤回者不是发送者
	MsgErrCode_withDraw_message_withDrawer_is_not_sender MsgErrCode = 2062
	// 设置好友备注名，反序列化 msg_struct.C2SSetFriendRemarkName
	MsgErrCode_proto_unmarshal_msg_struct_C2SSetFriendRemarkName_has_error MsgErrCode = 2070
	// 设置好友备注名，两者不是好友关系
	MsgErrCode_set_friend_remark_name_is_not_friend MsgErrCode = 2071
	// 设置好友备注名，备注名为空
	MsgErrCode_set_friend_remark_name_remark_name_is_empty MsgErrCode = 2072
	// 发送环信推送，反序列化 msg_struct.C2SHuanXinPush 失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SHuanXinPush_has_error MsgErrCode = 2080
	// 发送环信推送，对方不是你的好友
	MsgErrCode_huan_xin_push_is_not_your_friend MsgErrCode = 2081
	// 发送环信推送，你不是对方的好友
	MsgErrCode_huan_xin_push_you_are_not_his_friend MsgErrCode = 2082
	// 发送环信推送，获取对方推送消息失败
	MsgErrCode_huan_xin_push_get_friend_push_info_failed MsgErrCode = 2083
	// 发送环信推送，对方是IOS，不是安卓
	MsgErrCode_huan_xin_push_is_not_android MsgErrCode = 2084
	// 获取短信验证码，反序列化 msg_struct.C2SGetVerificationCode 失败
	MsgErrCode_proto_unmarshal_get_verification_code_has_error MsgErrCode = 2090
	// 获取短信验证码，手机号错误
	MsgErrCode_get_verification_code_phone_num_error MsgErrCode = 2091
	// 获取短信验证码，用途不明
	MsgErrCode_get_verification_code_action_has_error MsgErrCode = 2092
	// 获取短信验证码，（注册时)，时间未超时
	MsgErrCode_get_verification_code_register_not_timeout MsgErrCode = 2093
	// 获取短信验证码，（注册时)，帐号已存在
	MsgErrCode_get_verification_code_register_account_exist MsgErrCode = 2094
	// 获取短信验证码，（忘记密码时)，账户不存在
	MsgErrCode_get_verification_code_forget_password_account_is_not_exist MsgErrCode = 2095
	// 获取短信验证码，（忘记密码时)，时间未超时
	MsgErrCode_get_verification_code_forget_password_not_timeout MsgErrCode = 2096
	// 获取短信验证码，服务器内部错误
	MsgErrCode_get_verification_code_server_internal_error MsgErrCode = 2099
	// 忘记密码时，反序列化 msg_struct.C2SForgetPassword 失败
	MsgErrCode_proto_unmarshal_forget_password_has_error MsgErrCode = 2100
	// 忘记密码时，帐号为空
	MsgErrCode_forget_password_phone_num_is_empty MsgErrCode = 2101
	// 忘记密码时，验证码为空
	MsgErrCode_forget_password_verification_code_is_empty MsgErrCode = 2102
	// 忘记密码时，密码为空
	MsgErrCode_forget_password_password_is_empty MsgErrCode = 2103
	// 忘记密码时，验证码错误
	MsgErrCode_forget_password_verification_code_error MsgErrCode = 2104
	// 忘记密码时，服务器内部错误
	MsgErrCode_forget_password_server_internal_error MsgErrCode = 2109
	// 建立聊天群失败，反序列化msg_struct.C2SCreateChatGroup失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SCreateChatGroup_has_error MsgErrCode = 3000
	// 建立聊天群失败，被邀请者不是邀请者的好友
	MsgErrCode_create_chat_group_invitee_and_inviter_is_not_friend MsgErrCode = 3001
	// 建立聊天群失败, 原因是往表 chat_group 插入记录失败
	MsgErrCode_create_chat_group_insert_chat_group_fail MsgErrCode = 3002
	// 建立聊天群失败, 更新表 chat_group.chat_group_id 字段 失败
	MsgErrCode_create_chat_group_update_chat_group_uid_fail MsgErrCode = 3003
	// 建立聊天群失败,往 chat_group_create_log 插入记录失败
	MsgErrCode_create_chat_group_insert_chat_group_create_log_fail MsgErrCode = 3004
	// 建立聊天群失败,往 chat_group_member 插入记录失败
	MsgErrCode_create_chat_group_insert_chat_group_member_fail MsgErrCode = 3005
	// 建立聊天群失败,提交事务时发送错误
	MsgErrCode_create_chat_group_commit_error_when_create_group MsgErrCode = 3006
	// 建立聊天群失败，序列化群主信息失败
	MsgErrCode_create_chat_group_marshal_chat_group_owner_failed MsgErrCode = 3007
	// 建立聊天群失败，群主获取好友的简略信息失败
	MsgErrCode_create_chat_group_get_friend_brief_info_failed MsgErrCode = 3008
	// 反序列化 msg_struct.C2SReqJoinChatGroup失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SReqJoinChatGroup_has_error MsgErrCode = 3020
	// 群ID错误
	MsgErrCode_send_req_join_chat_group_group_id_error MsgErrCode = 3021
	// 用户已经是群成员
	MsgErrCode_send_req_join_chat_group_is_group_member MsgErrCode = 3022
	// 通过用户上传的群ID，查询群主失败
	MsgErrCode_send_req_join_chat_group_query_group_manager_failed MsgErrCode = 3023
	// 通知群主失败
	MsgErrCode_mq_group_manager_req_join_chat_group_failed MsgErrCode = 3024
	// 服务器禁止短时间内建立多个群,所以建群失败
	MsgErrCode_ban_on_create_chat_group_in_short_time MsgErrCode = 3025
	// 反序列化 msg_struct.C2SAgreeSomeOneReqJoinChatGroup失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SAgreeSomeOneReqJoinChatGroup_has_error MsgErrCode = 3030
	// 查询群ID失败
	MsgErrCode_send_agree_some_one_req_join_chat_group_query_group_id_failed MsgErrCode = 3031
	// 发送者不是群主
	MsgErrCode_send_agree_some_one_req_join_chat_group_sender_is_not_manager MsgErrCode = 3032
	// 未查询到申请加群记录
	MsgErrCode_send_agree_some_one_req_join_chat_group_query_reques_uid_failed MsgErrCode = 3033
	// 插入群成员列表失败
	MsgErrCode_send_agree_some_one_req_join_chat_group_insert_chat_group_member_failed MsgErrCode = 3034
	// 标识处理此消息失败
	MsgErrCode_send_agree_some_one_req_join_chat_group_update_chat_group_req_join_log_failed MsgErrCode = 3035
	// 通知申请者，发送到 MQ 失败
	MsgErrCode_send_agree_some_one_req_join_chat_group_notice_requester_failed MsgErrCode = 3036
	// 获取群成员失败
	MsgErrCode_send_agree_some_one_req_join_chat_group_get_members_failed MsgErrCode = 3037
	// 反序列化 msg_struct.C2SRefuseSomeOneReqJoinChatGroup失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SRefuseSomeOneReqJoinChatGroup_has_error MsgErrCode = 3040
	// C2SRefuseSomeOneReqJoinChatGroup消息值错误
	MsgErrCode_send_refuse_req_some_one_req_join_chat_group_error MsgErrCode = 3041
	// 标识处理此消息失败
	MsgErrCode_send_refuse_some_one_req_join_chat_group_update_chat_group_req_join_log_failed MsgErrCode = 3042
	// 反序列化 msg_struct.C2SChatGroupInfo失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SChatGroupInfo_has_error MsgErrCode = 3050
	// C2SChatGroupInfo消息值错误
	MsgErrCode_send_chat_group_info_group_id_error MsgErrCode = 3051
	// 获取群信息失败
	MsgErrCode_send_chat_group_info_get_group_info_failed MsgErrCode = 3052
	// 获取群成员列表失败
	MsgErrCode_send_chat_group_info_get_group_member_failed MsgErrCode = 3053
	// 反序列化 msg_struct.C2SInviteJoinChatGroup失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SInviteJoinChatGroup_has_error MsgErrCode = 3060
	// 群ID错误
	MsgErrCode_send_invite_join_chat_group_group_id_error MsgErrCode = 3061
	// 被邀请者ID错误
	MsgErrCode_send_invite_join_chat_group_invitee_id_error MsgErrCode = 3062
	// 被邀请者与邀请者不是好友关系
	MsgErrCode_send_invite_join_chat_group_is_not_friend_error MsgErrCode = 3063
	// 被邀请者已经进群
	MsgErrCode_send_invite_join_chat_group_has_joined_chat_group_error MsgErrCode = 3064
	// 被邀请者添加到chat_group_member失败
	MsgErrCode_send_invite_join_chat_group_insert_chat_group_member_failed MsgErrCode = 3065
	// 获取群成员列表失败
	MsgErrCode_send_invite_join_chat_group_get_chat_group_member_failed MsgErrCode = 3066
	// 反序列化 msg_struct.C2SCancelChatGroup失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SCancelChatGroup_has_error MsgErrCode = 3070
	// 群ID错误
	MsgErrCode_send_cancel_chat_group_group_id_error MsgErrCode = 3071
	// 用户不是群成员
	MsgErrCode_send_cancel_chat_group_is_not_member MsgErrCode = 3072
	// 用户是群主
	MsgErrCode_send_cancel_chat_group_is_creator MsgErrCode = 3073
	// 反序列化 msg_struct.C2SUnChatGroup失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SUnChatGroup_has_error MsgErrCode = 3080
	// 群ID错误
	MsgErrCode_send_un_chat_group_group_id_error MsgErrCode = 3081
	// 用户不是群主
	MsgErrCode_send_un_chat_group_is_not_creator MsgErrCode = 3082
	// 获取群成员列表失败
	MsgErrCode_send_un_chat_group_get_members_failed MsgErrCode = 3083
	// 反序列化 msg_struct.C2SChatGroupKick失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SChatGroupKick_has_error MsgErrCode = 3090
	// 群ID错误
	MsgErrCode_send_chat_group_kick_group_id_error MsgErrCode = 3091
	// 用户不是群主
	MsgErrCode_send_chat_group_kick_is_not_creator MsgErrCode = 3092
	// 用户不是群成员
	MsgErrCode_send_chat_group_user_is_not_member MsgErrCode = 3093
	// 获取群成员列表失败
	MsgErrCode_send_chat_group_kick_get_members_failed MsgErrCode = 3094
	// 反序列化 msg_struct.C2SChatGroupList失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SChatGroupList_has_error MsgErrCode = 3100
	// 读取用户群列表失败
	MsgErrCode_send_chat_group_list_get_chat_group_list_failed MsgErrCode = 3101
	// 反序列化 msg_struct.C2SGetOfflineGroupChatMsg失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SGetOfflineGroupChatMsg_has_error MsgErrCode = 3110
	// 群id不合法
	MsgErrCode_send_get_offline_group_chat_msg_group_id_illegal MsgErrCode = 3111
	// 服务器从redis读取群离线消息失败
	MsgErrCode_send_get_offlien_group_chat_msg_get_offline_msg_failed MsgErrCode = 3112
	// 用户撤回群聊消息，反序列化 msg_struct.C2SWithdrawGroupMessage 失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SWithdrawGroupMessage_has_error MsgErrCode = 3120
	// 用户撤回群聊消息，群聊消息撤回失败,可能因为已经超过 5 分钟
	MsgErrCode_withDraw_group_message_group_chat_withdraw_fail MsgErrCode = 3121
	// 用户撤回私聊消息时，撤回者不是发送者
	MsgErrCode_withDraw_group_message_withDrawer_is_not_sender MsgErrCode = 3122
	// 发送群聊消息时，反序列化 msg_struct.C2SGroupChat失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SGroupChat_has_error MsgErrCode = 3130
	// 发送群聊消息时，群消息 ChatMsg为空
	MsgErrCode_send_group_chat_msg_chat_msg_is_nil MsgErrCode = 3131
	// 发送群聊消息时，消息结构不合法
	MsgErrCode_send_group_chat_msg_chat_msg_is_illege MsgErrCode = 3132
	// 发送群聊消息时，发送者不是群成员
	MsgErrCode_send_group_chat_sender_is_not_chat_group_member MsgErrCode = 3133
	// 发送群聊消息时，序列化群消息失败
	MsgErrCode_proto_marshal_msg_struct_GroupMessage_has_error MsgErrCode = 3134
	// 发送群聊消息时，消息存入redis失败
	MsgErrCode_send_group_chat_msg_chat_msg_store_redis_failed MsgErrCode = 3135
	// 发送群聊消息时，获取群成员失败
	MsgErrCode_send_group_chat_msg_get_group_member_failed MsgErrCode = 3136
	// 发送群聊消息时，消息类型与对应结构不符（例如，消息类型为voice，但voiceMessage结构体为空）
	MsgErrCode_send_group_chat_msg_type_not_match_message MsgErrCode = 3137
	// 发送群聊消息时，语音url为空
	MsgErrCode_send_group_chat_msg_voice_url_is_empty MsgErrCode = 3138
	// 发送群聊消息时，语音过长
	MsgErrCode_send_group_chat_msg_voice_too_long MsgErrCode = 3139
	// 发送私聊消息时，文件url为空
	MsgErrCode_send_group_chat_msg_file_url_is_empty MsgErrCode = 3140
	// 发送私聊消息时，文件缩略图为空
	MsgErrCode_send_group_chat_msg_file_thumbnail_url_is_empty MsgErrCode = 3141
	// 发送私聊消息时，视频url为空
	MsgErrCode_send_group_chat_msg_video_url_is_empty MsgErrCode = 3142
	// 发送私聊消息时，视频缩略图url为空
	MsgErrCode_send_group_chat_msg_video_thumbnail_url_is_empty MsgErrCode = 3143
	// 设置朋友圈相册封面，反序列化 msg_struct.C2SSetWeiboCover 失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SSetWeiboCover_has_error MsgErrCode = 4000
	// 设置朋友圈相册封面，朋友圈相册封面图片url地址为空
	MsgErrCode_set_weibo_cover_cover_picture_is_empty MsgErrCode = 4001
	// 设置朋友圈相册封面，服务器内部错误
	MsgErrCode_set_weibo_cover_server_internal_error MsgErrCode = 4002
	// 发朋友圈，反序列化 msg_struct.C2SPublishWeibo失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SPublishWeibo_has_error MsgErrCode = 4010
	// 发朋友圈，朋友圈内容不合法
	MsgErrCode_publish_weibo_content_is_illegal MsgErrCode = 4011
	// 发朋友圈，朋友圈类型与内容不匹配
	MsgErrCode_publish_weibo_content_do_not_match_type MsgErrCode = 4012
	// 发朋友圈，朋友圈文字超出限制
	MsgErrCode_publish_weibo_text_out_of_limit MsgErrCode = 4013
	// 发朋友圈，朋友圈内容不只是文字，但url链接为空
	MsgErrCode_publish_weibo_url_is_empty MsgErrCode = 4014
	// 发朋友圈，url链接个数超出限制
	MsgErrCode_publish_weibo_url_out_of_limit MsgErrCode = 4015
	// 发朋友圈，服务器内部错误
	MsgErrCode_publish_weibo_server_internal_error MsgErrCode = 4016
	// 点赞朋友圈，反序列化 msg_struct.C2SLickWeibo 失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SLickWeibo_has_error MsgErrCode = 4020
	// 点赞朋友圈，朋友圈id错误（朋友圈不是自己发的，或者不存在，或者朋友圈已被删除）
	MsgErrCode_like_weibo_weibo_id_is_error MsgErrCode = 4021
	// 点赞朋友圈，发朋友圈的人，与点赞者不是好友
	MsgErrCode_like_weibo_weibo_liker_publisher_is_not_friend MsgErrCode = 4022
	// 点赞朋友圈，服务器内部错误
	MsgErrCode_like_weibo_server_internal_error MsgErrCode = 4024
	// 取消点赞朋友圈，反序列化 msg_struct.C2SCancelLikeWeibo 失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SCancelLikeWeibo_has_error MsgErrCode = 4030
	// 取消点赞朋友圈，朋友圈id错误（朋友圈不是自己发的，或者不存在，或者朋友圈已被删除）
	MsgErrCode_cancel_like_weibo_weibo_id_is_error MsgErrCode = 4031
	// 取消点赞朋友圈，服务器内部错误
	MsgErrCode_cancel_like_weibo_server_internal_error MsgErrCode = 4032
	// 评论朋友圈，反序列化 msg_struct.C2SReplyWeibo 失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SReplyWeibo_has_error MsgErrCode = 4040
	// 评论朋友圈，朋友圈id错误（朋友圈不是自己发的，或者不存在，或者朋友圈已被删除）
	MsgErrCode_reply_weibo_weibo_id_is_error MsgErrCode = 4041
	// 评论朋友圈，被评论者（可能是发朋友圈的人，也可能是评论朋友圈的人），与评论者不是好友
	MsgErrCode_reply_weibo_commentor_is_not_becommentor_friend MsgErrCode = 4042
	// 评论朋友圈，评论内容过长
	MsgErrCode_reply_weibo_comment_content_is_too_long MsgErrCode = 4043
	// 评论朋友圈，服务器内部错误
	MsgErrCode_reply_weibo_server_internal_error MsgErrCode = 4044
	// 删除朋友圈评论，反序列化 msg_struct.C2SDeleteWeiboReply 失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SDeleteWeiboReply_has_error MsgErrCode = 4050
	// 删除朋友圈评论，朋友圈id错误（朋友圈不是自己发的，或者不存在，或者朋友圈已被删除）
	MsgErrCode_delete_weibo_reply_weibo_id_is_error MsgErrCode = 4051
	// 删除朋友圈评论，评论id错误
	MsgErrCode_delete_weibo_reply_comment_id_is_error MsgErrCode = 4052
	// 删除朋友圈评论，服务器内部错误
	MsgErrCode_delete_weibo_reply_server_internal_error MsgErrCode = 4053
	// 查看自己朋友圈, 反序列化 msg_struct.C2SBrowseOwnWeibo 失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SBrowseOwnWeibo_has_error MsgErrCode = 4070
	// 查看自己朋友圈, 服务器内部错误
	MsgErrCode_browse_own_weibo_server_internal_error MsgErrCode = 4071
	// 删除朋友圈，反序列化 msg_struct.C2SDeleteWeibo 失败
	MsgErrCode_proto_unmarshal_msg_struct_C2SDeleteWeibo_has_error MsgErrCode = 4080
	// 删除朋友圈，朋友圈id错误（朋友圈不是自己发的，或者不存在，或者朋友圈已被删除）
	MsgErrCode_delete_weibo_weibo_id_is_error MsgErrCode = 4081
	// 删除朋友圈，服务器内部错误
	MsgErrCode_delete_weibo_server_internal_error MsgErrCode = 4082
)

var MsgErrCode_name = map[int32]string{
	0:    "no_error",
	100:  "proto_unmarshal_msg_struct_C2SRegisterAccount_failed",
	101:  "register_account_account_id_is_zero",
	102:  "register_account_password_is_empty",
	103:  "register_account_verification_is_empty",
	104:  "register_account_verification_is_error",
	105:  "register_account_account_is_already_used",
	106:  "register_access_mysql_has_error_when_create_account",
	110:  "proto_unmarshal_msg_struct_C2SLogin_failed",
	111:  "login_account_id_is_zero",
	112:  "login_account_or_pwd_is_wrong",
	113:  "login_access_mysql_has_error_when_load_account",
	114:  "login_account_is_out_of_service",
	120:  "proto_unmarshal_msg_struct_C2SDeviceInfo_has_error",
	121:  "device_info_device_info_is_empty",
	122:  "device_info_device_producter_is_empty",
	123:  "device_info_device_proto_marshal_msg_struct_DeviceInfo_has_error",
	124:  "device_info_account_device_info_save_into_redis_failed",
	125:  "device_info_device_info_account_save_into_redis_failed",
	126:  "device_info_save_into_mysql_failed",
	130:  "proto_unmarshal_set_user_name_has_error",
	131:  "set_user_name_user_name_is_set",
	132:  "set_user_name_user_name_is_illegal",
	133:  "set_user_name_user_name_has_been_set",
	134:  "set_user_name_user_name_is_exist",
	135:  "set_user_name_save_into_redis_failed",
	136:  "set_user_name_save_into_mysql_failed",
	140:  "proto_unmarshal_find_user_has_error",
	141:  "find_user_key_is_empty",
	142:  "find_user_user_is_not_exist",
	150:  "proto_unmarshal_set_head_portrait_has_error",
	151:  "set_head_portrait_head_portrait_url_is_empty",
	152:  "set_head_save_head_portrait_url_into_redis_failed",
	153:  "set_head_save_head_portrait_url_into_mysql_failed",
	160:  "proto_unmarshal_msg_struct_C2SChangePassword_has_error",
	161:  "change_password_new_password_is_empty",
	162:  "change_password_save_into_mysql_error",
	2000: "proto_unmarshal_msg_struct_C2SAddFriend_has_error",
	2001: "add_friend_param_error",
	2002: "add_friend_mysql_has_error_when_write",
	2003: "add_friend_sender_and_recevier_are_friends",
	2010: "proto_unmarshal_msg_struct_C2SAgreeBecomeFriend_has_error",
	2011: "agree_become_friend_mysql_has_error_when_write",
	2012: "agree_become_friend_sender_and_receiver_are_friends",
	2013: "agree_become_friend_mysql_table_friend_req_has_no_record",
	2014: "agree_become_friend_mysql_table_friend_req_has_read_error",
	2015: "agree_become_friend_can_not_be_friend_with_self",
	2020: "proto_unmarshal_msg_struct_C2SDeleteFriend_has_error",
	2021: "delete_friend_is_not_friend",
	2022: "delete_friend_server_internal_error",
	2030: "proto_unmarshal_msg_struct_C2SConfirmDeleteFriend_has_error",
	2031: "confirm_friend_is_not_friend",
	2032: "confirm_friend_server_internal_error",
	2040: "proto_unmarsharl_msg_struct_C2SPrivateChat_has_error",
	2041: "private_chat_receiver_illegal",
	2042: "private_chat_receiver_is_not_friend",
	2043: "private_chat_receiver_type_illegal",
	2044: "private_chat_message_type_not_match_message",
	2045: "private_chat_voice_url_is_empty",
	2046: "private_chat_voice_too_long",
	2047: "private_chat_file_url_is_empty",
	2048: "private_chat_file_thumbnail_url_is_empty",
	2049: "private_chat_video_url_is_empty",
	2050: "private_chat_video_thumbnail_url_is_empty",
	2051: "private_chat_card_message_is_empty",
	2060: "proto_unmarshal_msg_struct_C2SWithdrawMessage_has_error",
	2061: "withDraw_message_private_chat_withdraw_fail",
	2062: "withDraw_message_withDrawer_is_not_sender",
	2070: "proto_unmarshal_msg_struct_C2SSetFriendRemarkName_has_error",
	2071: "set_friend_remark_name_is_not_friend",
	2072: "set_friend_remark_name_remark_name_is_empty",
	2080: "proto_unmarshal_msg_struct_C2SHuanXinPush_has_error",
	2081: "huan_xin_push_is_not_your_friend",
	2082: "huan_xin_push_you_are_not_his_friend",
	2083: "huan_xin_push_get_friend_push_info_failed",
	2084: "huan_xin_push_is_not_android",
	2090: "proto_unmarshal_get_verification_code_has_error",
	2091: "get_verification_code_phone_num_error",
	2092: "get_verification_code_action_has_error",
	2093: "get_verification_code_register_not_timeout",
	2094: "get_verification_code_register_account_exist",
	2095: "get_verification_code_forget_password_account_is_not_exist",
	2096: "get_verification_code_forget_password_not_timeout",
	2099: "get_verification_code_server_internal_error",
	2100: "proto_unmarshal_forget_password_has_error",
	2101: "forget_password_phone_num_is_empty",
	2102: "forget_password_verification_code_is_empty",
	2103: "forget_password_password_is_empty",
	2104: "forget_password_verification_code_error",
	2109: "forget_password_server_internal_error",
	3000: "proto_unmarshal_msg_struct_C2SCreateChatGroup_has_error",
	3001: "create_chat_group_invitee_and_inviter_is_not_friend",
	3002: "create_chat_group_insert_chat_group_fail",
	3003: "create_chat_group_update_chat_group_uid_fail",
	3004: "create_chat_group_insert_chat_group_create_log_fail",
	3005: "create_chat_group_insert_chat_group_member_fail",
	3006: "create_chat_group_commit_error_when_create_group",
	3007: "create_chat_group_marshal_chat_group_owner_failed",
	3008: "create_chat_group_get_friend_brief_info_failed",
	3020: "proto_unmarshal_msg_struct_C2SReqJoinChatGroup_has_error",
	3021: "send_req_join_chat_group_group_id_error",
	3022: "send_req_join_chat_group_is_group_member",
	3023: "send_req_join_chat_group_query_group_manager_failed",
	3024: "mq_group_manager_req_join_chat_group_failed",
	3025: "ban_on_create_chat_group_in_short_time",
	3030: "proto_unmarshal_msg_struct_C2SAgreeSomeOneReqJoinChatGroup_has_error",
	3031: "send_agree_some_one_req_join_chat_group_query_group_id_failed",
	3032: "send_agree_some_one_req_join_chat_group_sender_is_not_manager",
	3033: "send_agree_some_one_req_join_chat_group_query_reques_uid_failed",
	3034: "send_agree_some_one_req_join_chat_group_insert_chat_group_member_failed",
	3035: "send_agree_some_one_req_join_chat_group_update_chat_group_req_join_log_failed",
	3036: "send_agree_some_one_req_join_chat_group_notice_requester_failed",
	3037: "send_agree_some_one_req_join_chat_group_get_members_failed",
	3040: "proto_unmarshal_msg_struct_C2SRefuseSomeOneReqJoinChatGroup_has_error",
	3041: "send_refuse_req_some_one_req_join_chat_group_error",
	3042: "send_refuse_some_one_req_join_chat_group_update_chat_group_req_join_log_failed",
	3050: "proto_unmarshal_msg_struct_C2SChatGroupInfo_has_error",
	3051: "send_chat_group_info_group_id_error",
	3052: "send_chat_group_info_get_group_info_failed",
	3053: "send_chat_group_info_get_group_member_failed",
	3060: "proto_unmarshal_msg_struct_C2SInviteJoinChatGroup_has_error",
	3061: "send_invite_join_chat_group_group_id_error",
	3062: "send_invite_join_chat_group_invitee_id_error",
	3063: "send_invite_join_chat_group_is_not_friend_error",
	3064: "send_invite_join_chat_group_has_joined_chat_group_error",
	3065: "send_invite_join_chat_group_insert_chat_group_member_failed",
	3066: "send_invite_join_chat_group_get_chat_group_member_failed",
	3070: "proto_unmarshal_msg_struct_C2SCancelChatGroup_has_error",
	3071: "send_cancel_chat_group_group_id_error",
	3072: "send_cancel_chat_group_is_not_member",
	3073: "send_cancel_chat_group_is_creator",
	3080: "proto_unmarshal_msg_struct_C2SUnChatGroup_has_error",
	3081: "send_un_chat_group_group_id_error",
	3082: "send_un_chat_group_is_not_creator",
	3083: "send_un_chat_group_get_members_failed",
	3090: "proto_unmarshal_msg_struct_C2SChatGroupKick_has_error",
	3091: "send_chat_group_kick_group_id_error",
	3092: "send_chat_group_kick_is_not_creator",
	3093: "send_chat_group_user_is_not_member",
	3094: "send_chat_group_kick_get_members_failed",
	3100: "proto_unmarshal_msg_struct_C2SChatGroupList_has_error",
	3101: "send_chat_group_list_get_chat_group_list_failed",
	3110: "proto_unmarshal_msg_struct_C2SGetOfflineGroupChatMsg_has_error",
	3111: "send_get_offline_group_chat_msg_group_id_illegal",
	3112: "send_get_offlien_group_chat_msg_get_offline_msg_failed",
	3120: "proto_unmarshal_msg_struct_C2SWithdrawGroupMessage_has_error",
	3121: "withDraw_group_message_group_chat_withdraw_fail",
	3122: "withDraw_group_message_withDrawer_is_not_sender",
	3130: "proto_unmarshal_msg_struct_C2SGroupChat_has_error",
	3131: "send_group_chat_msg_chat_msg_is_nil",
	3132: "send_group_chat_msg_chat_msg_is_illege",
	3133: "send_group_chat_sender_is_not_chat_group_member",
	3134: "proto_marshal_msg_struct_GroupMessage_has_error",
	3135: "send_group_chat_msg_chat_msg_store_redis_failed",
	3136: "send_group_chat_msg_get_group_member_failed",
	3137: "send_group_chat_msg_type_not_match_message",
	3138: "send_group_chat_msg_voice_url_is_empty",
	3139: "send_group_chat_msg_voice_too_long",
	3140: "send_group_chat_msg_file_url_is_empty",
	3141: "send_group_chat_msg_file_thumbnail_url_is_empty",
	3142: "send_group_chat_msg_video_url_is_empty",
	3143: "send_group_chat_msg_video_thumbnail_url_is_empty",
	4000: "proto_unmarshal_msg_struct_C2SSetWeiboCover_has_error",
	4001: "set_weibo_cover_cover_picture_is_empty",
	4002: "set_weibo_cover_server_internal_error",
	4010: "proto_unmarshal_msg_struct_C2SPublishWeibo_has_error",
	4011: "publish_weibo_content_is_illegal",
	4012: "publish_weibo_content_do_not_match_type",
	4013: "publish_weibo_text_out_of_limit",
	4014: "publish_weibo_url_is_empty",
	4015: "publish_weibo_url_out_of_limit",
	4016: "publish_weibo_server_internal_error",
	4020: "proto_unmarshal_msg_struct_C2SLickWeibo_has_error",
	4021: "like_weibo_weibo_id_is_error",
	4022: "like_weibo_weibo_liker_publisher_is_not_friend",
	4024: "like_weibo_server_internal_error",
	4030: "proto_unmarshal_msg_struct_C2SCancelLikeWeibo_has_error",
	4031: "cancel_like_weibo_weibo_id_is_error",
	4032: "cancel_like_weibo_server_internal_error",
	4040: "proto_unmarshal_msg_struct_C2SReplyWeibo_has_error",
	4041: "reply_weibo_weibo_id_is_error",
	4042: "reply_weibo_commentor_is_not_becommentor_friend",
	4043: "reply_weibo_comment_content_is_too_long",
	4044: "reply_weibo_server_internal_error",
	4050: "proto_unmarshal_msg_struct_C2SDeleteWeiboReply_has_error",
	4051: "delete_weibo_reply_weibo_id_is_error",
	4052: "delete_weibo_reply_comment_id_is_error",
	4053: "delete_weibo_reply_server_internal_error",
	4070: "proto_unmarshal_msg_struct_C2SBrowseOwnWeibo_has_error",
	4071: "browse_own_weibo_server_internal_error",
	4080: "proto_unmarshal_msg_struct_C2SDeleteWeibo_has_error",
	4081: "delete_weibo_weibo_id_is_error",
	4082: "delete_weibo_server_internal_error",
}

var MsgErrCode_value = map[string]int32{
	"no_error": 0,
	"proto_unmarshal_msg_struct_C2SRegisterAccount_failed":                           100,
	"register_account_account_id_is_zero":                                            101,
	"register_account_password_is_empty":                                             102,
	"register_account_verification_is_empty":                                         103,
	"register_account_verification_is_error":                                         104,
	"register_account_account_is_already_used":                                       105,
	"register_access_mysql_has_error_when_create_account":                            106,
	"proto_unmarshal_msg_struct_C2SLogin_failed":                                     110,
	"login_account_id_is_zero":                                                       111,
	"login_account_or_pwd_is_wrong":                                                  112,
	"login_access_mysql_has_error_when_load_account":                                 113,
	"login_account_is_out_of_service":                                                114,
	"proto_unmarshal_msg_struct_C2SDeviceInfo_has_error":                             120,
	"device_info_device_info_is_empty":                                               121,
	"device_info_device_producter_is_empty":                                          122,
	"device_info_device_proto_marshal_msg_struct_DeviceInfo_has_error":               123,
	"device_info_account_device_info_save_into_redis_failed":                         124,
	"device_info_device_info_account_save_into_redis_failed":                         125,
	"device_info_save_into_mysql_failed":                                             126,
	"proto_unmarshal_set_user_name_has_error":                                        130,
	"set_user_name_user_name_is_set":                                                 131,
	"set_user_name_user_name_is_illegal":                                             132,
	"set_user_name_user_name_has_been_set":                                           133,
	"set_user_name_user_name_is_exist":                                               134,
	"set_user_name_save_into_redis_failed":                                           135,
	"set_user_name_save_into_mysql_failed":                                           136,
	"proto_unmarshal_find_user_has_error":                                            140,
	"find_user_key_is_empty":                                                         141,
	"find_user_user_is_not_exist":                                                    142,
	"proto_unmarshal_set_head_portrait_has_error":                                    150,
	"set_head_portrait_head_portrait_url_is_empty":                                   151,
	"set_head_save_head_portrait_url_into_redis_failed":                              152,
	"set_head_save_head_portrait_url_into_mysql_failed":                              153,
	"proto_unmarshal_msg_struct_C2SChangePassword_has_error":                         160,
	"change_password_new_password_is_empty":                                          161,
	"change_password_save_into_mysql_error":                                          162,
	"proto_unmarshal_msg_struct_C2SAddFriend_has_error":                              2000,
	"add_friend_param_error":                                                         2001,
	"add_friend_mysql_has_error_when_write":                                          2002,
	"add_friend_sender_and_recevier_are_friends":                                     2003,
	"proto_unmarshal_msg_struct_C2SAgreeBecomeFriend_has_error":                      2010,
	"agree_become_friend_mysql_has_error_when_write":                                 2011,
	"agree_become_friend_sender_and_receiver_are_friends":                            2012,
	"agree_become_friend_mysql_table_friend_req_has_no_record":                       2013,
	"agree_become_friend_mysql_table_friend_req_has_read_error":                      2014,
	"agree_become_friend_can_not_be_friend_with_self":                                2015,
	"proto_unmarshal_msg_struct_C2SDeleteFriend_has_error":                           2020,
	"delete_friend_is_not_friend":                                                    2021,
	"delete_friend_server_internal_error":                                            2022,
	"proto_unmarshal_msg_struct_C2SConfirmDeleteFriend_has_error":                    2030,
	"confirm_friend_is_not_friend":                                                   2031,
	"confirm_friend_server_internal_error":                                           2032,
	"proto_unmarsharl_msg_struct_C2SPrivateChat_has_error":                           2040,
	"private_chat_receiver_illegal":                                                  2041,
	"private_chat_receiver_is_not_friend":                                            2042,
	"private_chat_receiver_type_illegal":                                             2043,
	"private_chat_message_type_not_match_message":                                    2044,
	"private_chat_voice_url_is_empty":                                                2045,
	"private_chat_voice_too_long":                                                    2046,
	"private_chat_file_url_is_empty":                                                 2047,
	"private_chat_file_thumbnail_url_is_empty":                                       2048,
	"private_chat_video_url_is_empty":                                                2049,
	"private_chat_video_thumbnail_url_is_empty":                                      2050,
	"private_chat_card_message_is_empty":                                             2051,
	"proto_unmarshal_msg_struct_C2SWithdrawMessage_has_error":                        2060,
	"withDraw_message_private_chat_withdraw_fail":                                    2061,
	"withDraw_message_withDrawer_is_not_sender":                                      2062,
	"proto_unmarshal_msg_struct_C2SSetFriendRemarkName_has_error":                    2070,
	"set_friend_remark_name_is_not_friend":                                           2071,
	"set_friend_remark_name_remark_name_is_empty":                                    2072,
	"proto_unmarshal_msg_struct_C2SHuanXinPush_has_error":                            2080,
	"huan_xin_push_is_not_your_friend":                                               2081,
	"huan_xin_push_you_are_not_his_friend":                                           2082,
	"huan_xin_push_get_friend_push_info_failed":                                      2083,
	"huan_xin_push_is_not_android":                                                   2084,
	"proto_unmarshal_get_verification_code_has_error":                                2090,
	"get_verification_code_phone_num_error":                                          2091,
	"get_verification_code_action_has_error":                                         2092,
	"get_verification_code_register_not_timeout":                                     2093,
	"get_verification_code_register_account_exist":                                   2094,
	"get_verification_code_forget_password_account_is_not_exist":                     2095,
	"get_verification_code_forget_password_not_timeout":                              2096,
	"get_verification_code_server_internal_error":                                    2099,
	"proto_unmarshal_forget_password_has_error":                                      2100,
	"forget_password_phone_num_is_empty":                                             2101,
	"forget_password_verification_code_is_empty":                                     2102,
	"forget_password_password_is_empty":                                              2103,
	"forget_password_verification_code_error":                                        2104,
	"forget_password_server_internal_error":                                          2109,
	"proto_unmarshal_msg_struct_C2SCreateChatGroup_has_error":                        3000,
	"create_chat_group_invitee_and_inviter_is_not_friend":                            3001,
	"create_chat_group_insert_chat_group_fail":                                       3002,
	"create_chat_group_update_chat_group_uid_fail":                                   3003,
	"create_chat_group_insert_chat_group_create_log_fail":                            3004,
	"create_chat_group_insert_chat_group_member_fail":                                3005,
	"create_chat_group_commit_error_when_create_group":                               3006,
	"create_chat_group_marshal_chat_group_owner_failed":                              3007,
	"create_chat_group_get_friend_brief_info_failed":                                 3008,
	"proto_unmarshal_msg_struct_C2SReqJoinChatGroup_has_error":                       3020,
	"send_req_join_chat_group_group_id_error":                                        3021,
	"send_req_join_chat_group_is_group_member":                                       3022,
	"send_req_join_chat_group_query_group_manager_failed":                            3023,
	"mq_group_manager_req_join_chat_group_failed":                                    3024,
	"ban_on_create_chat_group_in_short_time":                                         3025,
	"proto_unmarshal_msg_struct_C2SAgreeSomeOneReqJoinChatGroup_has_error":           3030,
	"send_agree_some_one_req_join_chat_group_query_group_id_failed":                  3031,
	"send_agree_some_one_req_join_chat_group_sender_is_not_manager":                  3032,
	"send_agree_some_one_req_join_chat_group_query_reques_uid_failed":                3033,
	"send_agree_some_one_req_join_chat_group_insert_chat_group_member_failed":        3034,
	"send_agree_some_one_req_join_chat_group_update_chat_group_req_join_log_failed":  3035,
	"send_agree_some_one_req_join_chat_group_notice_requester_failed":                3036,
	"send_agree_some_one_req_join_chat_group_get_members_failed":                     3037,
	"proto_unmarshal_msg_struct_C2SRefuseSomeOneReqJoinChatGroup_has_error":          3040,
	"send_refuse_req_some_one_req_join_chat_group_error":                             3041,
	"send_refuse_some_one_req_join_chat_group_update_chat_group_req_join_log_failed": 3042,
	"proto_unmarshal_msg_struct_C2SChatGroupInfo_has_error":                          3050,
	"send_chat_group_info_group_id_error":                                            3051,
	"send_chat_group_info_get_group_info_failed":                                     3052,
	"send_chat_group_info_get_group_member_failed":                                   3053,
	"proto_unmarshal_msg_struct_C2SInviteJoinChatGroup_has_error":                    3060,
	"send_invite_join_chat_group_group_id_error":                                     3061,
	"send_invite_join_chat_group_invitee_id_error":                                   3062,
	"send_invite_join_chat_group_is_not_friend_error":                                3063,
	"send_invite_join_chat_group_has_joined_chat_group_error":                        3064,
	"send_invite_join_chat_group_insert_chat_group_member_failed":                    3065,
	"send_invite_join_chat_group_get_chat_group_member_failed":                       3066,
	"proto_unmarshal_msg_struct_C2SCancelChatGroup_has_error":                        3070,
	"send_cancel_chat_group_group_id_error":                                          3071,
	"send_cancel_chat_group_is_not_member":                                           3072,
	"send_cancel_chat_group_is_creator":                                              3073,
	"proto_unmarshal_msg_struct_C2SUnChatGroup_has_error":                            3080,
	"send_un_chat_group_group_id_error":                                              3081,
	"send_un_chat_group_is_not_creator":                                              3082,
	"send_un_chat_group_get_members_failed":                                          3083,
	"proto_unmarshal_msg_struct_C2SChatGroupKick_has_error":                          3090,
	"send_chat_group_kick_group_id_error":                                            3091,
	"send_chat_group_kick_is_not_creator":                                            3092,
	"send_chat_group_user_is_not_member":                                             3093,
	"send_chat_group_kick_get_members_failed":                                        3094,
	"proto_unmarshal_msg_struct_C2SChatGroupList_has_error":                          3100,
	"send_chat_group_list_get_chat_group_list_failed":                                3101,
	"proto_unmarshal_msg_struct_C2SGetOfflineGroupChatMsg_has_error":                 3110,
	"send_get_offline_group_chat_msg_group_id_illegal":                               3111,
	"send_get_offlien_group_chat_msg_get_offline_msg_failed":                         3112,
	"proto_unmarshal_msg_struct_C2SWithdrawGroupMessage_has_error":                   3120,
	"withDraw_group_message_group_chat_withdraw_fail":                                3121,
	"withDraw_group_message_withDrawer_is_not_sender":                                3122,
	"proto_unmarshal_msg_struct_C2SGroupChat_has_error":                              3130,
	"send_group_chat_msg_chat_msg_is_nil":                                            3131,
	"send_group_chat_msg_chat_msg_is_illege":                                         3132,
	"send_group_chat_sender_is_not_chat_group_member":                                3133,
	"proto_marshal_msg_struct_GroupMessage_has_error":                                3134,
	"send_group_chat_msg_chat_msg_store_redis_failed":                                3135,
	"send_group_chat_msg_get_group_member_failed":                                    3136,
	"send_group_chat_msg_type_not_match_message":                                     3137,
	"send_group_chat_msg_voice_url_is_empty":                                         3138,
	"send_group_chat_msg_voice_too_long":                                             3139,
	"send_group_chat_msg_file_url_is_empty":                                          3140,
	"send_group_chat_msg_file_thumbnail_url_is_empty":                                3141,
	"send_group_chat_msg_video_url_is_empty":                                         3142,
	"send_group_chat_msg_video_thumbnail_url_is_empty":                               3143,
	"proto_unmarshal_msg_struct_C2SSetWeiboCover_has_error":                          4000,
	"set_weibo_cover_cover_picture_is_empty":                                         4001,
	"set_weibo_cover_server_internal_error":                                          4002,
	"proto_unmarshal_msg_struct_C2SPublishWeibo_has_error":                           4010,
	"publish_weibo_content_is_illegal":                                               4011,
	"publish_weibo_content_do_not_match_type":                                        4012,
	"publish_weibo_text_out_of_limit":                                                4013,
	"publish_weibo_url_is_empty":                                                     4014,
	"publish_weibo_url_out_of_limit":                                                 4015,
	"publish_weibo_server_internal_error":                                            4016,
	"proto_unmarshal_msg_struct_C2SLickWeibo_has_error":                              4020,
	"like_weibo_weibo_id_is_error":                                                   4021,
	"like_weibo_weibo_liker_publisher_is_not_friend":                                 4022,
	"like_weibo_server_internal_error":                                               4024,
	"proto_unmarshal_msg_struct_C2SCancelLikeWeibo_has_error":                        4030,
	"cancel_like_weibo_weibo_id_is_error":                                            4031,
	"cancel_like_weibo_server_internal_error":                                        4032,
	"proto_unmarshal_msg_struct_C2SReplyWeibo_has_error":                             4040,
	"reply_weibo_weibo_id_is_error":                                                  4041,
	"reply_weibo_commentor_is_not_becommentor_friend":                                4042,
	"reply_weibo_comment_content_is_too_long":                                        4043,
	"reply_weibo_server_internal_error":                                              4044,
	"proto_unmarshal_msg_struct_C2SDeleteWeiboReply_has_error":                       4050,
	"delete_weibo_reply_weibo_id_is_error":                                           4051,
	"delete_weibo_reply_comment_id_is_error":                                         4052,
	"delete_weibo_reply_server_internal_error":                                       4053,
	"proto_unmarshal_msg_struct_C2SBrowseOwnWeibo_has_error":                         4070,
	"browse_own_weibo_server_internal_error":                                         4071,
	"proto_unmarshal_msg_struct_C2SDeleteWeibo_has_error":                            4080,
	"delete_weibo_weibo_id_is_error":                                                 4081,
	"delete_weibo_server_internal_error":                                             4082,
}

func (x MsgErrCode) String() string {
	return proto.EnumName(MsgErrCode_name, int32(x))
}

func (MsgErrCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9dafb7dd6e5de257, []int{0}
}

func init() {
	proto.RegisterEnum("msg_err_code.MsgErrCode", MsgErrCode_name, MsgErrCode_value)
}

func init() { proto.RegisterFile("msg_err_code.proto", fileDescriptor_9dafb7dd6e5de257) }

var fileDescriptor_9dafb7dd6e5de257 = []byte{
	// 2684 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x5a, 0x69, 0xb0, 0x1d, 0x45,
	0xf5, 0xe7, 0x7e, 0xf9, 0xd7, 0xbf, 0xba, 0xa8, 0xba, 0x5d, 0xfd, 0xc1, 0xb9, 0x25, 0x90, 0xc9,
	0x42, 0x42, 0x08, 0x10, 0x20, 0x81, 0xb0, 0x6f, 0x79, 0x0f, 0x31, 0x90, 0x90, 0x54, 0x52, 0x16,
	0x7e, 0x9b, 0x9a, 0x3b, 0xd3, 0xf7, 0xde, 0xe6, 0xcd, 0xed, 0xbe, 0xaf, 0x67, 0xe6, 0xdd, 0x3c,
	0x5c, 0x8a, 0xc5, 0x05, 0x17, 0xf8, 0xe0, 0x12, 0x62, 0x95, 0x56, 0x91, 0x68, 0xa9, 0x25, 0x5b,
	0x54, 0xc0, 0x80, 0x64, 0x71, 0x47, 0x45, 0x0d, 0xe0, 0xca, 0xa2, 0x18, 0x15, 0xab, 0x5c, 0xd1,
	0x72, 0x01, 0x54, 0xb0, 0xba, 0x7b, 0x96, 0x9e, 0x99, 0x9e, 0xb9, 0xf7, 0x55, 0xf9, 0xe5, 0xe5,
	0xde, 0xee, 0xdf, 0xe9, 0xf3, 0x3b, 0xa7, 0xbb, 0xcf, 0x39, 0x7d, 0x6e, 0x00, 0x1a, 0x86, 0x7d,
	0x07, 0x73, 0xee, 0x78, 0xcc, 0xc7, 0xeb, 0x47, 0x9c, 0x45, 0x0c, 0x9d, 0xa8, 0x8f, 0xad, 0x7b,
	0xe4, 0x3a, 0x00, 0xb6, 0x85, 0xfd, 0xab, 0x39, 0x9f, 0x61, 0x3e, 0x46, 0x27, 0x82, 0xff, 0xa7,
	0x4c, 0xcc, 0x32, 0x0e, 0x4f, 0x40, 0x17, 0x82, 0xf3, 0xa4, 0x8c, 0x13, 0xd3, 0xa1, 0xcb, 0xc3,
	0x81, 0x1b, 0x38, 0x42, 0x38, 0x8c, 0x78, 0xec, 0x45, 0xce, 0xcc, 0x86, 0x5d, 0x3b, 0x71, 0x9f,
	0x84, 0x11, 0xe6, 0x57, 0x79, 0x1e, 0x8b, 0x69, 0xe4, 0xf4, 0x5c, 0x12, 0x60, 0x1f, 0xfa, 0xe8,
	0x34, 0xb0, 0x8a, 0x27, 0x73, 0x8e, 0x9b, 0x4c, 0xa6, 0xff, 0x12, 0xdf, 0x21, 0xa1, 0x73, 0x13,
	0xe6, 0x0c, 0x62, 0xb4, 0x06, 0xac, 0xac, 0x00, 0x47, 0x6e, 0x18, 0x8e, 0x19, 0x97, 0x30, 0x3c,
	0x1c, 0x45, 0x8b, 0xb0, 0x87, 0xd6, 0x81, 0x35, 0x15, 0xdc, 0x02, 0xe6, 0xa4, 0x47, 0x3c, 0x37,
	0x22, 0x8c, 0xe6, 0xd8, 0xfe, 0x74, 0x58, 0x69, 0xe2, 0x00, 0x9d, 0x09, 0xd6, 0xd6, 0x13, 0x0d,
	0x1d, 0x37, 0xe0, 0xd8, 0xf5, 0x17, 0x9d, 0x38, 0xc4, 0x3e, 0x24, 0xe8, 0x02, 0xb0, 0x51, 0x47,
	0xe3, 0x30, 0x74, 0x86, 0x8b, 0xe1, 0x7c, 0xe0, 0x0c, 0xdc, 0x64, 0x49, 0x67, 0x3c, 0xc0, 0xd4,
	0xf1, 0x38, 0x76, 0x23, 0x9c, 0x2e, 0x04, 0x6f, 0x44, 0xeb, 0xc1, 0xba, 0x66, 0x4f, 0x6e, 0x65,
	0x7d, 0x42, 0x53, 0xff, 0x51, 0x74, 0x32, 0xe8, 0x04, 0x72, 0xc4, 0xe0, 0x34, 0x86, 0x56, 0x80,
	0x53, 0x8a, 0xb3, 0x8c, 0x3b, 0xa3, 0xb1, 0x44, 0x8c, 0x39, 0xa3, 0x7d, 0x38, 0x42, 0x1b, 0xc0,
	0xfa, 0x0c, 0x52, 0x4b, 0x33, 0x60, 0xae, 0x9f, 0x91, 0x9c, 0x47, 0xab, 0x80, 0x5d, 0x52, 0x1a,
	0x3a, 0x2c, 0x8e, 0x1c, 0xd6, 0x73, 0x42, 0xcc, 0x17, 0x88, 0x87, 0x21, 0x47, 0x9b, 0xc0, 0x86,
	0x66, 0x4b, 0x66, 0xb1, 0x40, 0x6e, 0xa1, 0x3d, 0x96, 0xab, 0x83, 0xbb, 0xd1, 0xa9, 0x60, 0xb9,
	0x2f, 0x67, 0x1c, 0x22, 0xa6, 0xf4, 0xcf, 0xd9, 0xd6, 0x2d, 0xa2, 0xd3, 0xc1, 0x6a, 0x03, 0x6a,
	0xc4, 0x99, 0x1f, 0x7b, 0xc2, 0xe9, 0x19, 0xf4, 0x26, 0x34, 0x0b, 0xae, 0x34, 0x43, 0x23, 0xe6,
	0x18, 0x98, 0x19, 0x69, 0xbd, 0x0d, 0x5d, 0x0c, 0x36, 0xe9, 0xab, 0xa4, 0x96, 0xeb, 0x63, 0xa1,
	0xbb, 0x20, 0x3e, 0x45, 0xcc, 0xe1, 0xd8, 0x27, 0x61, 0xba, 0x49, 0x6f, 0x2f, 0xcb, 0x9a, 0xd6,
	0xa9, 0x91, 0x7d, 0x87, 0x38, 0xf7, 0x66, 0x1d, 0x6a, 0xa3, 0x12, 0xdc, 0x3b, 0xd1, 0x99, 0xe0,
	0xb4, 0xb2, 0xbb, 0x43, 0x1c, 0x89, 0xf3, 0xc8, 0x1d, 0xea, 0x0e, 0xb1, 0x66, 0xcc, 0xad, 0x2d,
	0xb4, 0x0a, 0x2c, 0x2b, 0xce, 0xe6, 0x9f, 0x48, 0x28, 0x04, 0xe1, 0x6d, 0x2d, 0x74, 0x1a, 0x58,
	0xd9, 0x00, 0x22, 0x41, 0x80, 0xfb, 0x6e, 0x00, 0xdf, 0xd5, 0x42, 0xa7, 0x83, 0x53, 0xeb, 0x80,
	0x42, 0x6b, 0x17, 0x63, 0x2a, 0xd7, 0x7c, 0x77, 0x0b, 0xad, 0x06, 0xcb, 0x1b, 0xd6, 0xc4, 0xbb,
	0x49, 0x18, 0xc1, 0xf7, 0x18, 0x56, 0xac, 0xf1, 0xcf, 0x7b, 0x1b, 0xa1, 0x05, 0x17, 0xdd, 0xde,
	0x42, 0x6b, 0xc1, 0xaa, 0xb2, 0x8f, 0x7a, 0x84, 0xfa, 0x4a, 0x36, 0xf7, 0xcf, 0x07, 0x5b, 0xe8,
	0x24, 0xf0, 0x86, 0x7c, 0x66, 0x0e, 0x2f, 0xe6, 0xe7, 0xe9, 0x8e, 0x16, 0x5a, 0x0e, 0x4e, 0xca,
	0x27, 0xe5, 0x1f, 0x12, 0x3a, 0x94, 0x45, 0x09, 0xfd, 0x3b, 0x5b, 0xe8, 0x1c, 0x70, 0x86, 0x69,
	0x33, 0x06, 0xd8, 0xf5, 0x9d, 0x11, 0xe3, 0x11, 0x77, 0x49, 0xa4, 0x29, 0xdc, 0xd3, 0x42, 0xe7,
	0x82, 0x33, 0x0d, 0x88, 0xc2, 0xb7, 0x98, 0x07, 0x39, 0x8d, 0xbb, 0x5a, 0x68, 0x13, 0x38, 0x37,
	0x13, 0x91, 0x36, 0x1b, 0xe0, 0x15, 0x87, 0xed, 0x9d, 0x5e, 0xae, 0xe0, 0xbd, 0x8f, 0xb5, 0xd0,
	0x25, 0x60, 0x53, 0xf3, 0x85, 0x9e, 0x19, 0xb8, 0xb4, 0x8f, 0x77, 0xa4, 0x41, 0x39, 0xb7, 0xef,
	0xee, 0x16, 0x5a, 0x07, 0x56, 0x7b, 0x72, 0x3a, 0x0f, 0xda, 0x14, 0x8f, 0x0d, 0x11, 0x7c, 0x9f,
	0x11, 0x5b, 0xde, 0x53, 0xb5, 0xee, 0x7e, 0x69, 0x4c, 0x33, 0xa9, 0xab, 0x7c, 0xff, 0x4d, 0x9c,
	0x60, 0xaa, 0xf3, 0x39, 0xd6, 0x16, 0x1b, 0xec, 0xfa, 0xbe, 0xd3, 0x53, 0x53, 0x23, 0x97, 0xbb,
	0xc3, 0x64, 0xf2, 0xc9, 0xb6, 0x20, 0xa0, 0x4d, 0x1a, 0x23, 0xe2, 0x98, 0x93, 0x08, 0xc3, 0xa7,
	0xda, 0xe8, 0x6c, 0xb0, 0x4e, 0xc3, 0x86, 0x98, 0xfa, 0x22, 0xe4, 0x53, 0xdf, 0xe1, 0xd8, 0xc3,
	0x0b, 0x44, 0x7c, 0xe1, 0x38, 0x99, 0x0e, 0xe1, 0xd3, 0x6d, 0x74, 0x39, 0xb8, 0x68, 0x02, 0xe3,
	0x3e, 0xc7, 0x78, 0x33, 0xf6, 0xd8, 0x10, 0x57, 0x98, 0x3f, 0xd3, 0x46, 0x1b, 0xc1, 0x7a, 0x57,
	0x20, 0x9c, 0xae, 0x84, 0x4c, 0xc1, 0xf2, 0xd9, 0x36, 0xba, 0x10, 0x6c, 0x34, 0x09, 0x95, 0xe8,
	0x92, 0x85, 0x12, 0xdd, 0xe7, 0xda, 0xe8, 0x32, 0x70, 0x61, 0xbd, 0xba, 0xc8, 0xed, 0x06, 0xd9,
	0x10, 0xc7, 0xf3, 0x52, 0x3f, 0x15, 0x47, 0xce, 0x63, 0xdc, 0x87, 0xcf, 0x4b, 0x6b, 0x97, 0x28,
	0x2e, 0xf2, 0x68, 0x62, 0xed, 0xcf, 0xdb, 0xe8, 0x3c, 0x70, 0xb6, 0x49, 0xde, 0x73, 0xa9, 0xbc,
	0x71, 0xdd, 0x6c, 0x64, 0x4c, 0xa2, 0x81, 0x13, 0xe2, 0xa0, 0x07, 0x7f, 0xd1, 0x46, 0x17, 0x4d,
	0xaa, 0x47, 0x66, 0x71, 0x80, 0xa3, 0xaa, 0x7b, 0x7f, 0xdd, 0x16, 0x97, 0xdb, 0x97, 0x93, 0xe9,
	0xc2, 0xc9, 0xdd, 0x56, 0xdf, 0xe0, 0x6f, 0xda, 0x22, 0x8a, 0x14, 0x11, 0x22, 0xe7, 0x89, 0x20,
	0x40, 0x23, 0xcc, 0xa9, 0x9b, 0x1e, 0xce, 0x17, 0xdb, 0xe8, 0x4a, 0x70, 0xc9, 0x84, 0x1b, 0xc3,
	0x68, 0x8f, 0xf0, 0x61, 0x0d, 0x9b, 0x3f, 0xb5, 0xd1, 0x0a, 0x70, 0xb2, 0xa7, 0x30, 0x66, 0x3a,
	0x7f, 0x6e, 0x8b, 0xf8, 0x57, 0x82, 0x98, 0xf9, 0xbc, 0x64, 0x70, 0x0b, 0x2f, 0x13, 0xda, 0xc1,
	0xc9, 0x82, 0x1b, 0xe1, 0x99, 0x81, 0xab, 0xc7, 0xa7, 0x97, 0xdb, 0x68, 0x25, 0x38, 0x65, 0xa4,
	0xe6, 0x1c, 0x4f, 0x4c, 0x66, 0xc7, 0x25, 0x4d, 0x03, 0xaf, 0xb4, 0x55, 0x78, 0x35, 0x62, 0x0a,
	0x9c, 0x5f, 0x6d, 0x8b, 0xcc, 0x62, 0x46, 0x46, 0x8b, 0x23, 0x9c, 0x2d, 0xf9, 0xaf, 0xb6, 0x0a,
	0xa4, 0x1a, 0x70, 0x88, 0xc3, 0xd0, 0xed, 0x63, 0x85, 0x13, 0x6b, 0x0e, 0xdd, 0xc8, 0x1b, 0xa4,
	0xc3, 0xf0, 0xdf, 0x6d, 0x74, 0x2a, 0xb0, 0x0b, 0x12, 0x0b, 0x4c, 0xe4, 0xce, 0x42, 0xec, 0xfc,
	0x8f, 0xdc, 0x65, 0x03, 0x2a, 0x62, 0xcc, 0x09, 0x44, 0x59, 0xf4, 0x5a, 0x5b, 0x64, 0xc8, 0x02,
	0xa2, 0x47, 0x82, 0xd2, 0x32, 0xaf, 0xb7, 0xd1, 0x59, 0x60, 0x6d, 0x15, 0x14, 0x0d, 0xe2, 0x61,
	0x97, 0xba, 0x24, 0x28, 0xc2, 0x6f, 0x86, 0x55, 0x6e, 0xc4, 0xc7, 0xac, 0x88, 0xba, 0x05, 0xa2,
	0xf5, 0xe0, 0x74, 0x03, 0xaa, 0x66, 0xd5, 0x5b, 0x61, 0xc5, 0x99, 0x9e, 0xcb, 0xfd, 0xcc, 0x51,
	0x19, 0xf0, 0x36, 0x88, 0x2e, 0x05, 0x17, 0x34, 0x1f, 0xc7, 0x1b, 0x48, 0x34, 0xf0, 0xb9, 0x3b,
	0xde, 0x96, 0x08, 0x6b, 0x29, 0x11, 0x8a, 0xad, 0x10, 0x77, 0x6c, 0x96, 0xbb, 0xe3, 0x6c, 0xf5,
	0x82, 0xde, 0x71, 0x22, 0x2d, 0x53, 0x06, 0xbc, 0x43, 0x1a, 0x52, 0x91, 0x48, 0x07, 0xf2, 0x53,
	0xa1, 0x62, 0x10, 0xbc, 0x13, 0x4e, 0xbe, 0x2e, 0xbb, 0x70, 0xa4, 0x2e, 0xc9, 0x4e, 0x3c, 0x74,
	0xf9, 0xdc, 0xf5, 0xc5, 0xb2, 0x66, 0x0f, 0x4c, 0x6b, 0x81, 0x2c, 0xa2, 0x08, 0x54, 0x56, 0x5c,
	0x68, 0x47, 0xf0, 0x2e, 0x69, 0x4e, 0x0d, 0xb4, 0x24, 0xa6, 0xdc, 0xb7, 0x17, 0x8a, 0x18, 0xda,
	0x4c, 0xef, 0xcd, 0xb1, 0x4b, 0xdf, 0x4a, 0xe8, 0x8e, 0x38, 0x1c, 0xe8, 0xc9, 0x0f, 0x8a, 0xa2,
	0x67, 0x10, 0xbb, 0xd4, 0xd9, 0x4d, 0xa8, 0x33, 0x12, 0xb3, 0x09, 0x9b, 0x45, 0x16, 0xf3, 0x94,
	0xd2, 0x3e, 0xc9, 0xbe, 0x08, 0x5b, 0x64, 0xb1, 0x0c, 0xc7, 0x02, 0x3b, 0x10, 0x39, 0x5c, 0x41,
	0xf7, 0x4b, 0xd7, 0x16, 0xa1, 0xfd, 0xdc, 0x16, 0xa5, 0x41, 0x14, 0x8b, 0x49, 0xee, 0xfe, 0x24,
	0x14, 0x71, 0xc4, 0xc8, 0xc0, 0xa5, 0x3e, 0x67, 0xc4, 0x87, 0x9f, 0x82, 0x22, 0xd2, 0x96, 0xcd,
	0x13, 0x8b, 0x16, 0xde, 0x43, 0xe2, 0x25, 0xa8, 0x99, 0xf6, 0x39, 0x28, 0x52, 0xa5, 0x19, 0x35,
	0x1a, 0x30, 0x8a, 0x1d, 0x1a, 0xa7, 0x69, 0xf5, 0x1e, 0x88, 0xce, 0x00, 0x6b, 0xcc, 0x58, 0xd7,
	0x93, 0x9f, 0xf3, 0x85, 0xef, 0x85, 0x22, 0xaf, 0x9a, 0xc1, 0xd9, 0xbb, 0x4a, 0xf0, 0x8f, 0xc8,
	0x10, 0xb3, 0x38, 0x82, 0xf7, 0x41, 0x51, 0x41, 0x4d, 0x10, 0x48, 0x6b, 0x6d, 0x55, 0xa6, 0xdd,
	0x0f, 0xd1, 0x15, 0xe0, 0x62, 0xb3, 0x48, 0x8f, 0x71, 0x31, 0x91, 0x95, 0x1f, 0xda, 0x3b, 0x27,
	0xaf, 0xf3, 0x1e, 0x80, 0xa2, 0xfa, 0x98, 0x6e, 0x01, 0x9d, 0xeb, 0x01, 0x79, 0xf8, 0xcc, 0x72,
	0xe6, 0xd0, 0xfd, 0xc5, 0x24, 0x28, 0x94, 0x4a, 0xd7, 0x92, 0x8e, 0xdc, 0x7d, 0x0f, 0xca, 0xa0,
	0x50, 0x9e, 0xcf, 0x77, 0x24, 0x3b, 0xd5, 0x0f, 0x49, 0x3f, 0x97, 0x81, 0x55, 0x5a, 0x99, 0xc0,
	0xc3, 0x10, 0xad, 0x01, 0x2b, 0x2a, 0x2b, 0x57, 0xaa, 0xb8, 0x2f, 0x41, 0xf1, 0x20, 0x99, 0xbc,
	0xb0, 0xe2, 0x7b, 0x50, 0x9e, 0xa3, 0x32, 0xda, 0xec, 0x8b, 0x43, 0x53, 0xc4, 0xb1, 0x19, 0xf9,
	0xaa, 0x16, 0x49, 0xec, 0x1a, 0xce, 0xe2, 0x91, 0xe6, 0x99, 0x83, 0x96, 0xb8, 0xc6, 0xc9, 0xab,
	0x5b, 0x46, 0xad, 0xbe, 0x44, 0x10, 0xba, 0x40, 0x22, 0x8c, 0x65, 0x25, 0xa4, 0x3e, 0x97, 0xb3,
	0xd6, 0x23, 0x96, 0x88, 0xf6, 0x26, 0xc9, 0x10, 0xf3, 0x48, 0x1f, 0x91, 0xe1, 0xef, 0x51, 0x4b,
	0x1c, 0xc8, 0x2a, 0x3c, 0x1e, 0xf9, 0xe5, 0x11, 0xe2, 0x2b, 0x91, 0x2f, 0xd7, 0x72, 0x2b, 0x6b,
	0x48, 0x30, 0x01, 0xeb, 0x2b, 0xc9, 0xc7, 0x2c, 0x71, 0x7b, 0xa7, 0x91, 0x1c, 0xe2, 0x61, 0x17,
	0x73, 0x25, 0x75, 0xc8, 0x42, 0xe7, 0x83, 0x73, 0xaa, 0x52, 0x1e, 0x1b, 0x0e, 0x49, 0x64, 0xe8,
	0x52, 0xc8, 0x69, 0x78, 0xd8, 0x12, 0xc7, 0xbe, 0x2a, 0x96, 0x6e, 0x85, 0x36, 0xc4, 0xc6, 0x34,
	0x51, 0x86, 0x7d, 0x78, 0xc4, 0x12, 0xa5, 0x6b, 0x55, 0x4e, 0x8b, 0x5c, 0x5d, 0x4e, 0x70, 0xaf,
	0x10, 0xba, 0x8e, 0x5a, 0xa2, 0x00, 0x9d, 0xd4, 0x5b, 0x9a, 0xbf, 0x96, 0x11, 0x6a, 0xda, 0xee,
	0x27, 0x2c, 0x71, 0x0c, 0xc3, 0xb4, 0xbc, 0xbc, 0x91, 0x11, 0x5a, 0x50, 0xad, 0xbc, 0x94, 0x96,
	0x9b, 0xdf, 0x93, 0x5b, 0x5c, 0x8b, 0x26, 0x61, 0xc1, 0x89, 0xf0, 0xfb, 0x72, 0xbf, 0x6a, 0xe1,
	0xf3, 0x31, 0xe6, 0x8b, 0x99, 0x6f, 0xa8, 0xdb, 0xcf, 0x5d, 0xf1, 0x03, 0x4b, 0x44, 0x80, 0xe1,
	0x7c, 0x69, 0xd6, 0xb4, 0x4a, 0x22, 0x71, 0xcc, 0x12, 0xd1, 0xb3, 0xeb, 0x52, 0x87, 0x65, 0xdb,
	0x51, 0xd8, 0x68, 0x27, 0x1c, 0x30, 0xae, 0x62, 0x0c, 0x7c, 0xd2, 0x42, 0x5b, 0xc0, 0xec, 0x14,
	0x8f, 0x8c, 0x5d, 0x6c, 0x88, 0xb7, 0x53, 0xdc, 0xe0, 0xc0, 0x1f, 0x5b, 0x68, 0x33, 0xb8, 0x4c,
	0xda, 0xa8, 0xca, 0xf0, 0x50, 0x14, 0xe1, 0x22, 0x8e, 0x4c, 0x32, 0x39, 0x39, 0xd5, 0xd8, 0x87,
	0x3f, 0x59, 0xd2, 0x1a, 0xc9, 0x93, 0x24, 0xb9, 0x7c, 0x89, 0x6b, 0xe0, 0x4f, 0x2d, 0x34, 0x0b,
	0xae, 0x58, 0x1a, 0x0f, 0x8e, 0xe7, 0x63, 0x1c, 0x66, 0xf7, 0x0b, 0xfb, 0xf0, 0x67, 0x16, 0xda,
	0x0a, 0xae, 0x99, 0x76, 0x95, 0xc6, 0xdb, 0x83, 0x7d, 0xf8, 0x8c, 0x85, 0x76, 0x82, 0x6d, 0xd3,
	0xae, 0x56, 0xbd, 0xf8, 0x19, 0x2a, 0xbd, 0xc7, 0xd8, 0x87, 0xcf, 0x2e, 0xc9, 0x4e, 0xca, 0x22,
	0x51, 0xb6, 0x2a, 0x43, 0xa3, 0x9c, 0xd9, 0x73, 0x96, 0x48, 0x6d, 0xd3, 0xae, 0x22, 0x2e, 0xa0,
	0xb2, 0x2c, 0xeb, 0x12, 0x3c, 0x6f, 0xa1, 0x6b, 0xc1, 0xd5, 0x93, 0xae, 0x5d, 0x2f, 0x0e, 0xa7,
	0x38, 0x42, 0x2f, 0x58, 0xe8, 0x02, 0xb0, 0x21, 0xb9, 0x26, 0x42, 0x44, 0x92, 0x68, 0x64, 0xa4,
	0x04, 0x7f, 0x69, 0xa1, 0x5d, 0xe0, 0x7a, 0x5d, 0xf0, 0x7f, 0xe0, 0xe0, 0xe3, 0x16, 0xba, 0x18,
	0x9c, 0x3f, 0xb1, 0x8f, 0xa1, 0xac, 0x28, 0x35, 0x01, 0x7f, 0x67, 0x89, 0x27, 0x8e, 0x24, 0x54,
	0x38, 0x26, 0x3d, 0x56, 0x8e, 0x24, 0xbf, 0xb7, 0x44, 0x5e, 0x35, 0x23, 0x71, 0xe1, 0x6b, 0x42,
	0xeb, 0x0f, 0x96, 0xea, 0x00, 0x35, 0x0a, 0x14, 0x8f, 0xdf, 0x1f, 0xad, 0xc9, 0x05, 0xf3, 0x16,
	0x99, 0xca, 0xea, 0x76, 0xe6, 0x6f, 0x39, 0x4b, 0x95, 0xf3, 0x26, 0x05, 0xc8, 0xbf, 0xe7, 0x2c,
	0x6b, 0x04, 0xd2, 0x3c, 0x9a, 0x89, 0xfc, 0x43, 0xa6, 0xa6, 0x46, 0x11, 0x3d, 0xcd, 0x26, 0x52,
	0xff, 0xb4, 0x44, 0x92, 0x6f, 0x92, 0x12, 0x56, 0x88, 0x31, 0xec, 0x57, 0x0f, 0xce, 0xcb, 0xd2,
	0x33, 0xcd, 0x34, 0x9b, 0xaf, 0xf6, 0x2b, 0x32, 0xed, 0x34, 0x7a, 0x06, 0x37, 0x88, 0xbf, 0x6a,
	0x4d, 0x51, 0xa3, 0xb8, 0xd4, 0xc3, 0x81, 0x69, 0x5b, 0x5e, 0xb3, 0x44, 0x35, 0x14, 0x26, 0x6d,
	0x0e, 0x0f, 0x07, 0x0d, 0x3b, 0xf2, 0xba, 0xa5, 0xde, 0x3c, 0x46, 0x6c, 0x1a, 0x43, 0x55, 0xba,
	0xba, 0xb9, 0x23, 0x4a, 0xb7, 0x7a, 0xa8, 0xcc, 0x2a, 0x8c, 0xc3, 0x5b, 0x3a, 0x93, 0x5f, 0x3a,
	0x6f, 0x31, 0x9e, 0xa7, 0xdb, 0x73, 0x0d, 0x71, 0xd3, 0x31, 0x7a, 0x5f, 0x1d, 0x2e, 0x21, 0x9c,
	0x32, 0x79, 0x7f, 0x27, 0x73, 0x44, 0x3c, 0x29, 0x62, 0x7d, 0xa0, 0xb3, 0x84, 0x7b, 0x7d, 0x1d,
	0xf1, 0xe6, 0x34, 0xde, 0x1f, 0xea, 0x98, 0xee, 0xf5, 0x9c, 0x00, 0x95, 0x98, 0x7f, 0xb8, 0x1e,
	0x59, 0xe2, 0xfe, 0x91, 0x8e, 0x6a, 0x9f, 0x17, 0x91, 0x7a, 0xb3, 0x38, 0xd9, 0x96, 0x8f, 0x76,
	0xb2, 0x12, 0xa5, 0xa2, 0xbc, 0x6a, 0xe6, 0x9e, 0xa5, 0x98, 0xb9, 0x95, 0x84, 0x7a, 0x17, 0xe7,
	0xe3, 0x9d, 0xec, 0x2a, 0x6a, 0x9a, 0x02, 0x01, 0x2a, 0x9d, 0x66, 0x39, 0x96, 0x68, 0xfc, 0x44,
	0x07, 0xcd, 0x80, 0xcb, 0x9b, 0x35, 0x5e, 0x83, 0xa3, 0xed, 0xbd, 0x5e, 0x40, 0x28, 0x96, 0x7a,
	0x05, 0x81, 0x6d, 0x61, 0x5f, 0x53, 0xfd, 0xe9, 0x8e, 0x28, 0x35, 0xa5, 0x6a, 0xa1, 0x8a, 0x29,
	0x70, 0x5a, 0x6f, 0xca, 0xc6, 0x4e, 0xd8, 0xcf, 0x9d, 0x9d, 0x36, 0x80, 0x3e, 0xd3, 0x41, 0x97,
	0x80, 0x4d, 0x45, 0x31, 0x4c, 0x2b, 0x62, 0xda, 0x8a, 0xe2, 0x7b, 0x42, 0xfc, 0xb3, 0x1d, 0x74,
	0x15, 0xb8, 0x74, 0xba, 0x86, 0x87, 0xa4, 0x5d, 0xed, 0x7a, 0x1c, 0x90, 0x1e, 0xcb, 0x7a, 0x18,
	0xe9, 0x55, 0x57, 0x30, 0x8d, 0x45, 0xb1, 0xf3, 0xf1, 0xf9, 0x26, 0xa9, 0xda, 0xfe, 0xc7, 0x17,
	0x3a, 0x93, 0x7b, 0xd9, 0x99, 0x77, 0x35, 0x8e, 0x8f, 0xe6, 0x47, 0xb2, 0xe4, 0x97, 0xec, 0x83,
	0x50, 0x24, 0xde, 0x17, 0x1d, 0x51, 0x43, 0x4e, 0x42, 0x4a, 0xdf, 0x63, 0xf8, 0x58, 0x7e, 0x58,
	0x34, 0x70, 0xb1, 0x38, 0xab, 0xc4, 0x3f, 0x78, 0xa8, 0x93, 0xb7, 0x11, 0x0c, 0x26, 0xd4, 0xb8,
	0xf9, 0xb0, 0x51, 0x57, 0x81, 0x58, 0x18, 0x31, 0x8e, 0x8b, 0xbf, 0x64, 0x1c, 0xe9, 0xa8, 0x1e,
	0x4e, 0x55, 0xaa, 0x2e, 0x63, 0x1e, 0xed, 0x64, 0xf9, 0xae, 0x24, 0x51, 0xd3, 0x4e, 0xfc, 0x4a,
	0xad, 0xc7, 0x0c, 0x5d, 0xc5, 0xaf, 0xe6, 0x37, 0xde, 0x08, 0xce, 0x9a, 0x8b, 0x5f, 0xcb, 0xc3,
	0x5a, 0x09, 0x58, 0xed, 0x31, 0x7e, 0xbd, 0xd6, 0x35, 0x4d, 0xad, 0xc6, 0x6f, 0xd4, 0xf3, 0xae,
	0x76, 0x1c, 0xbf, 0xa9, 0xdd, 0x4d, 0x13, 0xb8, 0x46, 0xc7, 0xb7, 0xa6, 0x88, 0x44, 0xbb, 0x70,
	0x74, 0x03, 0x26, 0x5d, 0x36, 0xc3, 0x16, 0x0a, 0x3f, 0xb0, 0xdd, 0x6d, 0x2b, 0x7e, 0x91, 0x33,
	0x16, 0xd3, 0x8e, 0x27, 0xe7, 0xd5, 0xdf, 0x11, 0xf1, 0xa2, 0x98, 0x6b, 0x2d, 0x87, 0x7d, 0xb6,
	0x72, 0x57, 0x11, 0x6c, 0x6e, 0x0e, 0xec, 0xb7, 0x27, 0xb7, 0xfe, 0x77, 0xc4, 0xdd, 0x80, 0x84,
	0x03, 0x49, 0x4c, 0xef, 0x65, 0xd9, 0x68, 0x35, 0x58, 0x3e, 0x52, 0x93, 0x99, 0x2a, 0x1a, 0x61,
	0xd5, 0xf6, 0x49, 0x43, 0xd2, 0x3d, 0xb6, 0xfc, 0xa5, 0xd5, 0x08, 0xf3, 0x99, 0x76, 0x86, 0xc4,
	0x91, 0x82, 0xf7, 0xda, 0xb2, 0xe7, 0x5b, 0x40, 0x47, 0x78, 0x77, 0x94, 0xfe, 0x5a, 0x1e, 0x90,
	0x21, 0x89, 0xe0, 0x7d, 0x36, 0xb2, 0xc1, 0x1b, 0x8b, 0xa8, 0x82, 0xaf, 0xef, 0xb7, 0x65, 0x3b,
	0xba, 0x02, 0x28, 0xac, 0xf2, 0x80, 0x2d, 0x1b, 0xf0, 0x05, 0x90, 0xd9, 0x4b, 0x07, 0xec, 0xc9,
	0xa1, 0x66, 0x2b, 0xf1, 0xe6, 0xca, 0x2e, 0x7a, 0xd0, 0x46, 0x2b, 0xc0, 0xc9, 0x01, 0x99, 0xc3,
	0xc9, 0xf2, 0xea, 0xaf, 0xfa, 0x1f, 0x07, 0x0a, 0xf2, 0x90, 0x2d, 0x1e, 0xf9, 0x15, 0x88, 0x18,
	0xe0, 0x4e, 0xc2, 0xad, 0xd2, 0x5a, 0x79, 0x58, 0xba, 0x5e, 0x13, 0x32, 0xd3, 0x3e, 0x68, 0x4f,
	0x5b, 0x55, 0x6d, 0x25, 0x73, 0xb8, 0x4c, 0xfe, 0xb0, 0x74, 0x4f, 0x52, 0xf9, 0x34, 0xda, 0x70,
	0x44, 0x6e, 0x71, 0x15, 0x69, 0x66, 0x75, 0xd4, 0x16, 0xcf, 0x9b, 0x49, 0x4f, 0xa5, 0x51, 0xb0,
	0x58, 0x26, 0xf4, 0xb8, 0x8d, 0x56, 0x82, 0x53, 0xb8, 0x98, 0xaa, 0xa5, 0xf2, 0x6d, 0x5b, 0x5c,
	0x7f, 0x1d, 0xe3, 0xb1, 0xe1, 0x10, 0xd3, 0x88, 0x65, 0x3e, 0x94, 0xbf, 0x8b, 0x25, 0x43, 0x89,
	0x3f, 0xbf, 0x23, 0x0d, 0x30, 0x48, 0xe9, 0x07, 0x3a, 0x0b, 0x47, 0xdf, 0xb5, 0x45, 0x35, 0xa6,
	0xa3, 0xcd, 0x86, 0x3e, 0x61, 0x4f, 0x6e, 0xc5, 0xa8, 0x1f, 0xb2, 0xa4, 0xa5, 0xd2, 0x66, 0xcd,
	0xdc, 0xa7, 0x6c, 0x51, 0xa9, 0x26, 0x3f, 0x9c, 0x29, 0x3d, 0xba, 0x4e, 0xdd, 0xea, 0xa7, 0x65,
	0x78, 0x30, 0x40, 0x53, 0x33, 0x74, 0xf0, 0x0f, 0x6d, 0x74, 0x16, 0x58, 0x6b, 0x00, 0x9b, 0xad,
	0xf8, 0x91, 0x3d, 0xf9, 0x77, 0xec, 0xcd, 0x9c, 0x8d, 0x43, 0xbc, 0x7d, 0x4c, 0xcb, 0x5b, 0xf6,
	0xa2, 0x24, 0xd6, 0x95, 0xd3, 0x0e, 0x1b, 0xd3, 0x46, 0x7f, 0xfd, 0xd6, 0x9e, 0x5c, 0x47, 0x6b,
	0xfe, 0xd2, 0xd4, 0xbc, 0x24, 0xaf, 0x7b, 0xc1, 0xa4, 0xaa, 0x93, 0xfe, 0x62, 0x8b, 0x74, 0x53,
	0x00, 0x99, 0x79, 0xfc, 0xd5, 0xde, 0x0c, 0x1f, 0x3f, 0xbe, 0xac, 0x75, 0xec, 0xf8, 0xb2, 0xd6,
	0x0b, 0xc7, 0x97, 0xb5, 0xf6, 0xfe, 0x6a, 0xd9, 0x09, 0xdd, 0xff, 0x93, 0xbc, 0x36, 0xfe, 0x37,
	0x00, 0x00, 0xff, 0xff, 0xc6, 0xbc, 0xa1, 0x4e, 0xf8, 0x25, 0x00, 0x00,
}
