// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: msg_id.proto

package msg_id

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 警告， c2s_create_character， c2s_login 这三对协议的值不可改变，新增协议值不能小于 65541，否则程序会出问题
type NetMsgId int32

const (
	NetMsgId_msg_star_id NetMsgId = 0
	// 获取 GATE 地址
	NetMsgId_C2l_gate_addr NetMsgId = 60000
	NetMsgId_L2c_gate_addr NetMsgId = 60001
	// 错误码通知
	NetMsgId_S2CErrorCode       NetMsgId = 60002
	NetMsgId_C2SRegisterAccount NetMsgId = 65536
	NetMsgId_S2CRegisterAccount NetMsgId = 65537
	//登录
	NetMsgId_C2SLogin NetMsgId = 65538
	NetMsgId_S2CLogin NetMsgId = 65539
	//创建角色
	NetMsgId_C2SCreateCharacter NetMsgId = 65540
	NetMsgId_S2CCreateCharacter NetMsgId = 65541
	//客户端主动退出
	NetMsgId_C2SLogout NetMsgId = 65542
	NetMsgId_S2CLogout NetMsgId = 65543
	// 客户端发送心跳包
	NetMsgId_C2SHeartbeat NetMsgId = 65544
	NetMsgId_S2CHeartbeat NetMsgId = 65545
	// 服务器把客户端踢下线
	NetMsgId_S2CKick        NetMsgId = 65546
	NetMsgId_S2CRepeatLogin NetMsgId = 65547
	// 改名
	NetMsgId_C2SRename NetMsgId = 65548
	NetMsgId_S2CRename NetMsgId = 65549
	// 客户端上传硬件信息
	NetMsgId_C2SDeviceInfo NetMsgId = 65550
	NetMsgId_S2CDeviceInfo NetMsgId = 65551
	// 用户名
	NetMsgId_C2SSetUserName NetMsgId = 65552
	NetMsgId_S2CSetUserName NetMsgId = 65553
	// 头像
	NetMsgId_C2SSetHeadPortrait NetMsgId = 65554
	NetMsgId_S2CSetHeadPortrait NetMsgId = 65555
	// 修改密码
	NetMsgId_C2SChangePassword NetMsgId = 65556
	NetMsgId_S2CChangePassword NetMsgId = 65557
	// 忘记密码
	NetMsgId_C2SForgetPassword NetMsgId = 65558
	NetMsgId_S2CForgetPassword NetMsgId = 65559
	// 获取短信验证码
	NetMsgId_C2SGetVerificationCode NetMsgId = 65560
	NetMsgId_S2CGetVerificationCode NetMsgId = 65561
	// 用户名、密码登录
	NetMsgId_C2SUsernameLogin NetMsgId = 65562
	NetMsgId_S2CUsernameLogin NetMsgId = 65563
	// 客户端把收到的最后一条消息的时间戳上报给服务器
	NetMsgId_C2SLastMsgTimeStamp NetMsgId = 65600
	// 客户端向服务端获取历史聊天记录
	NetMsgId_C2SGetChatRecords NetMsgId = 65602
	NetMsgId_S2CGetChatRecords NetMsgId = 65603
	// 发送私聊信息
	NetMsgId_C2SPrivateChat NetMsgId = 65604
	NetMsgId_MQPrivateChat  NetMsgId = 65607
	NetMsgId_S2CPrivateChat NetMsgId = 65605
	// B 收到 A 的消息
	NetMsgId_S2CRecvPrivateChat NetMsgId = 65606
	// 收到"我"在其他终端上发出的消息
	// 比如 a  登录了 APP 和 WEB 端的 IM, 在 APP 上发给别人的私聊消息, WEB 上也能看到
	NetMsgId_S2COtherTerminalPrivateChat NetMsgId = 65613
	// 用户登录后, 向服务端发送收到的最后一条聊天记录的时间戳,用来查询离线消息
	NetMsgId_C2SGetOfflinePrivateChatMsg NetMsgId = 65608
	NetMsgId_S2CGetOfflinePrivateChatMsg NetMsgId = 65609
	// 即将发送图片给服务器
	NetMsgId_C2SPicWillBeSend NetMsgId = 65610
	NetMsgId_S2CPicWillBeSend NetMsgId = 65611
	// 账号在其他地方登录
	NetMsgId_S2CLoginSomewhereElse NetMsgId = 65612
	// A 撤回已经发送的消息
	NetMsgId_C2SWithdrawMessage NetMsgId = 65614
	NetMsgId_S2CWithdrawMessage NetMsgId = 65616
	// 加好友
	NetMsgId_C2SAddFriend     NetMsgId = 65650
	NetMsgId_MQAddFriend      NetMsgId = 65651
	NetMsgId_S2CAddFriend     NetMsgId = 65652
	NetMsgId_S2CRecvAddFriend NetMsgId = 65653
	// 同意成为好友
	NetMsgId_C2SAgreeBecomeFriend     NetMsgId = 65660
	NetMsgId_MQAgreeBecomeFriend      NetMsgId = 65661
	NetMsgId_S2CAgreeBecomeFriend     NetMsgId = 65662
	NetMsgId_S2CRecvAgreeBecomeFriend NetMsgId = 65663
	// 比如 a 登录了 APP 和 WEB 端的 IM, 在 APP 上同意别人的好友请求, WEB 上也能看到和别人成为好友
	NetMsgId_S2COtherTerminalAgreeBecomeFriend NetMsgId = 65664
	// 登录后, 请求
	// 标记一条好友请求已读
	NetMsgId_C2SReadFriendReq NetMsgId = 65670
	NetMsgId_S2CReadFriendReq NetMsgId = 65672
	// 删除好友
	NetMsgId_C2SDeleteFriend     NetMsgId = 65680
	NetMsgId_MQDeleteFriend      NetMsgId = 65681
	NetMsgId_S2CDeleteFriend     NetMsgId = 65682
	NetMsgId_S2CRecvDeleteFriend NetMsgId = 65683
	// 被删除的好友，确认被删除消息
	NetMsgId_C2SConfirmDeleteFriend NetMsgId = 65690
	NetMsgId_S2CConfirmDeleteFriend NetMsgId = 65691
	// 建立群聊
	NetMsgId_C2SCreateChatGroup     NetMsgId = 65700
	NetMsgId_MQCreateChatGroup      NetMsgId = 65701
	NetMsgId_S2CCreateChatGroup     NetMsgId = 65702
	NetMsgId_S2CRecvCreateChatGroup NetMsgId = 65703
	// 用户主动加入聊天群
	NetMsgId_C2SReqJoinChatGroup        NetMsgId = 65710
	NetMsgId_S2CRecvReqJoinChatGroup    NetMsgId = 65711
	NetMsgId_MQReqJoinChatGroup         NetMsgId = 65712
	NetMsgId_S2CSomeOneReqJoinChatGroup NetMsgId = 65713
	// 群主同意用户加群
	NetMsgId_C2SAgreeSomeOneReqJoinChatGroup            NetMsgId = 65720
	NetMsgId_MQAgreeSomeOneReqJoinChatGroup             NetMsgId = 65721
	NetMsgId_MQManagerAgreeSomeOneReqJoinChatGroup      NetMsgId = 65722
	NetMsgId_S2CManagerAgreeSomeOneReqJoinChatGroup     NetMsgId = 65723
	NetMsgId_S2CManagerAgreeJoinChatGroup               NetMsgId = 65724
	NetMsgId_S2CRecvManagerAgreeSomeOneReqJoinChatGroup NetMsgId = 65725
	// 群主拒绝用户加群
	NetMsgId_C2SRefuseSomeOneReqJoinChatGroup NetMsgId = 65730
	NetMsgId_MQRefuseSomeOneReqJoinChatGroup  NetMsgId = 65731
	NetMsgId_S2CManagerRefuseJoinChatGroup    NetMsgId = 65732
	// 拉取群成员列表
	NetMsgId_C2SChatGroupInfo NetMsgId = 65740
	NetMsgId_S2CChatGroupInfo NetMsgId = 65741
	// 群成员邀请好友进群
	NetMsgId_C2SInviteJoinChatGroup     NetMsgId = 65750
	NetMsgId_MQInviteJoinChatGroup      NetMsgId = 65751
	NetMsgId_S2CInviteYouJoinChatGroup  NetMsgId = 65752
	NetMsgId_S2CRecvInviteJoinChatGroup NetMsgId = 65753
	// 群成员退群
	NetMsgId_C2SCancelChatGroup        NetMsgId = 65760
	NetMsgId_MQCancelChatGroup         NetMsgId = 65761
	NetMsgId_S2CSomeOneCancelChatGroup NetMsgId = 65762
	NetMsgId_S2CRecvCancelChatGroup    NetMsgId = 65763
	// 群主解散群
	NetMsgId_C2SUnChatGroup     NetMsgId = 65770
	NetMsgId_MQUnChatGroup      NetMsgId = 65771
	NetMsgId_S2CUnChatGroup     NetMsgId = 65772
	NetMsgId_S2CRecvUnChatGroup NetMsgId = 65773
	// 群主踢人
	NetMsgId_C2SChatGroupKick            NetMsgId = 65780
	NetMsgId_MQChatGroupKick             NetMsgId = 65781
	NetMsgId_S2CManagerKickSomeOne       NetMsgId = 65782
	NetMsgId_S2CKickedByChatGroupManager NetMsgId = 65783
	NetMsgId_S2CRecvChatGroupKick        NetMsgId = 65784
	// 用户获取群列表
	NetMsgId_C2SChatGroupList NetMsgId = 65790
	NetMsgId_S2CChatGroupList NetMsgId = 65791
	// 发送群聊信息
	NetMsgId_C2SGroupChat                 NetMsgId = 65800
	NetMsgId_S2CGroupChat                 NetMsgId = 65801
	NetMsgId_MQGroupChat                  NetMsgId = 65802
	NetMsgId_S2CRecvGroupChat             NetMsgId = 65803
	NetMsgId_C2SChatGroupLastMsgTimeStamp NetMsgId = 65804
	// 获取群聊离线消息
	NetMsgId_C2SGetOfflineGroupChatMsg NetMsgId = 65810
	NetMsgId_S2CGetOfflineGroupChatMsg NetMsgId = 65811
	// 撤回群聊消息
	NetMsgId_C2SWithdrawGroupMessage NetMsgId = 65820
	NetMsgId_S2CWithdrawGroupMessage NetMsgId = 65822
	// 查找用户
	NetMsgId_C2SFindUser NetMsgId = 66000
	NetMsgId_S2CFindUser NetMsgId = 66001
	// 用户好友拉黑名单
	NetMsgId_C2SAddFriendBlackList NetMsgId = 66010
	NetMsgId_S2CAddFriendBlackList NetMsgId = 66011
	// 用户好友移出黑名单
	NetMsgId_C2SMoveOutFriendBlackList NetMsgId = 66020
	NetMsgId_S2CMoveOutFriendBlackList NetMsgId = 66021
	// 用户获取黑名单列表
	NetMsgId_C2SGetFriendBlackList NetMsgId = 66030
	NetMsgId_S2CGetFriendBlackList NetMsgId = 66031
	// 设置朋友圈相册封面
	NetMsgId_C2SSetWeiboCover NetMsgId = 67000
	NetMsgId_S2CSetWeiboCover NetMsgId = 67001
	// 点赞朋友圈相册封面
	NetMsgId_C2SLikeFriendWeiboCover NetMsgId = 67010
	NetMsgId_S2CLikeFriendWeiboCover NetMsgId = 67011
	// 获取某人朋友圈相册封面（可以包括自己)
	NetMsgId_C2SGetWeiboCover NetMsgId = 67012
	NetMsgId_S2CGetWeiboCover NetMsgId = 67013
	// 发朋友圈
	NetMsgId_C2SPublishWeibo     NetMsgId = 67020
	NetMsgId_MQPublishWeibo      NetMsgId = 67021
	NetMsgId_S2CPublishWeibo     NetMsgId = 67022
	NetMsgId_S2CRecvPublishWeibo NetMsgId = 67023
	// 点赞朋友圈
	NetMsgId_C2SLikeWeibo     NetMsgId = 67030
	NetMsgId_MQLikeWeibo      NetMsgId = 67031
	NetMsgId_S2CLikeWeibo     NetMsgId = 67032
	NetMsgId_S2CRecvLikeWeibo NetMsgId = 67033
	// 取消点赞朋友圈
	NetMsgId_C2SCancelLikeWeibo NetMsgId = 67040
	NetMsgId_S2CCancelLikeWeibo NetMsgId = 67041
	// 评论朋友圈
	NetMsgId_C2SReplyWeibo     NetMsgId = 67050
	NetMsgId_MQReplyWeibo      NetMsgId = 67051
	NetMsgId_S2CReplyWeibo     NetMsgId = 67052
	NetMsgId_S2CRecvReplyWeibo NetMsgId = 67053
	// 朋友圈删除评论
	NetMsgId_C2SDeleteReplyWeibo NetMsgId = 67060
	NetMsgId_S2CDeleteReplyWeibo NetMsgId = 67061
	// 删除朋友圈
	NetMsgId_C2SDeleteWeibo     NetMsgId = 67070
	NetMsgId_MQDeleteWeibo      NetMsgId = 67071
	NetMsgId_S2CDeleteWeibo     NetMsgId = 67072
	NetMsgId_S2CRecvDeleteWeibo NetMsgId = 67073
	// 浏览某人朋友圈
	NetMsgId_C2SBrowseSomeoneWeibo NetMsgId = 67080
	NetMsgId_S2CBrowseSomeoneWeibo NetMsgId = 67081
	// 浏览所有朋友圈
	NetMsgId_C2SBrowseAllWeibo NetMsgId = 67100
	NetMsgId_S2CBrowseAllWeibo NetMsgId = 67101
	// 设置不看某好友朋友圈开关
	NetMsgId_C2SDontLookFriendWeibo NetMsgId = 67110
	NetMsgId_S2CDontLookFriendWeibo NetMsgId = 67111
	// 设置不允许某好友看自己朋友圈开关
	NetMsgId_C2SForbiddenFriendLookWeibo NetMsgId = 67120
	NetMsgId_S2CForbiddenFriendLookWeibo NetMsgId = 67121
	// 设置是否允许陌生人查看自己的10条朋友圈
	NetMsgId_C2SAllowStrangerLookWeibo NetMsgId = 67130
	NetMsgId_S2CAllowStrangerLookWeibo NetMsgId = 67131
	// 设置允许朋友查看自己朋友圈的范围
	NetMsgId_C2SFriendLookWeiboStrategy NetMsgId = 67140
	NetMsgId_S2CFriendLookWeiboStrategy NetMsgId = 67141
	// 获取不看好友朋友圈的好友列表
	NetMsgId_C2SGetDontLookFriendWeiboList NetMsgId = 67150
	NetMsgId_S2CGetDontLookFriendWeiboList NetMsgId = 67151
	// 获取禁止好友看我朋友圈的好友列表
	NetMsgId_C2SGetForbiddenFriendLookWeiboList NetMsgId = 67160
	NetMsgId_S2CGetForbiddenFriendLookWeiboList NetMsgId = 67161
	// 获取是否允许陌生人查看朋友圈开关
	NetMsgId_C2SIsAllowStrangerLookWeibo NetMsgId = 67170
	NetMsgId_S2CIsAllowStrangerLookWeibo NetMsgId = 67171
	// 获取允许好友查看朋友圈时间范围
	NetMsgId_C2SGetFriendLookWeiboStrategy NetMsgId = 67180
	NetMsgId_S2CGetFriendLookWeiboStrategy NetMsgId = 67181
	// 设置好友备注名
	NetMsgId_C2SSetFriendRemarkName NetMsgId = 67132
	NetMsgId_S2CSetFriendRemarkName NetMsgId = 67133
	// 发送环信推送
	NetMsgId_C2SHuanXinPush NetMsgId = 70000
	NetMsgId_S2CHuanXinPush NetMsgId = 70001
	// 第三方平台帐号登录
	NetMsgId_C2SThirdPlatformAccountLogin NetMsgId = 80000
	NetMsgId_S2CThirdPlatformAccountLogin NetMsgId = 80001
)

var NetMsgId_name = map[int32]string{
	0:     "msg_star_id",
	60000: "C2l_gate_addr",
	60001: "L2c_gate_addr",
	60002: "S2CErrorCode",
	65536: "C2SRegisterAccount",
	65537: "S2CRegisterAccount",
	65538: "C2SLogin",
	65539: "S2CLogin",
	65540: "C2SCreateCharacter",
	65541: "S2CCreateCharacter",
	65542: "C2SLogout",
	65543: "S2CLogout",
	65544: "C2SHeartbeat",
	65545: "S2CHeartbeat",
	65546: "S2CKick",
	65547: "S2CRepeatLogin",
	65548: "C2SRename",
	65549: "S2CRename",
	65550: "C2SDeviceInfo",
	65551: "S2CDeviceInfo",
	65552: "C2SSetUserName",
	65553: "S2CSetUserName",
	65554: "C2SSetHeadPortrait",
	65555: "S2CSetHeadPortrait",
	65556: "C2SChangePassword",
	65557: "S2CChangePassword",
	65558: "C2SForgetPassword",
	65559: "S2CForgetPassword",
	65560: "C2SGetVerificationCode",
	65561: "S2CGetVerificationCode",
	65562: "C2SUsernameLogin",
	65563: "S2CUsernameLogin",
	65600: "C2SLastMsgTimeStamp",
	65602: "C2SGetChatRecords",
	65603: "S2CGetChatRecords",
	65604: "C2SPrivateChat",
	65607: "MQPrivateChat",
	65605: "S2CPrivateChat",
	65606: "S2CRecvPrivateChat",
	65613: "S2COtherTerminalPrivateChat",
	65608: "C2SGetOfflinePrivateChatMsg",
	65609: "S2CGetOfflinePrivateChatMsg",
	65610: "C2SPicWillBeSend",
	65611: "S2CPicWillBeSend",
	65612: "S2CLoginSomewhereElse",
	65614: "C2SWithdrawMessage",
	65616: "S2CWithdrawMessage",
	65650: "C2SAddFriend",
	65651: "MQAddFriend",
	65652: "S2CAddFriend",
	65653: "S2CRecvAddFriend",
	65660: "C2SAgreeBecomeFriend",
	65661: "MQAgreeBecomeFriend",
	65662: "S2CAgreeBecomeFriend",
	65663: "S2CRecvAgreeBecomeFriend",
	65664: "S2COtherTerminalAgreeBecomeFriend",
	65670: "C2SReadFriendReq",
	65672: "S2CReadFriendReq",
	65680: "C2SDeleteFriend",
	65681: "MQDeleteFriend",
	65682: "S2CDeleteFriend",
	65683: "S2CRecvDeleteFriend",
	65690: "C2SConfirmDeleteFriend",
	65691: "S2CConfirmDeleteFriend",
	65700: "C2SCreateChatGroup",
	65701: "MQCreateChatGroup",
	65702: "S2CCreateChatGroup",
	65703: "S2CRecvCreateChatGroup",
	65710: "C2SReqJoinChatGroup",
	65711: "S2CRecvReqJoinChatGroup",
	65712: "MQReqJoinChatGroup",
	65713: "S2CSomeOneReqJoinChatGroup",
	65720: "C2SAgreeSomeOneReqJoinChatGroup",
	65721: "MQAgreeSomeOneReqJoinChatGroup",
	65722: "MQManagerAgreeSomeOneReqJoinChatGroup",
	65723: "S2CManagerAgreeSomeOneReqJoinChatGroup",
	65724: "S2CManagerAgreeJoinChatGroup",
	65725: "S2CRecvManagerAgreeSomeOneReqJoinChatGroup",
	65730: "C2SRefuseSomeOneReqJoinChatGroup",
	65731: "MQRefuseSomeOneReqJoinChatGroup",
	65732: "S2CManagerRefuseJoinChatGroup",
	65740: "C2SChatGroupInfo",
	65741: "S2CChatGroupInfo",
	65750: "C2SInviteJoinChatGroup",
	65751: "MQInviteJoinChatGroup",
	65752: "S2CInviteYouJoinChatGroup",
	65753: "S2CRecvInviteJoinChatGroup",
	65760: "C2SCancelChatGroup",
	65761: "MQCancelChatGroup",
	65762: "S2CSomeOneCancelChatGroup",
	65763: "S2CRecvCancelChatGroup",
	65770: "C2SUnChatGroup",
	65771: "MQUnChatGroup",
	65772: "S2CUnChatGroup",
	65773: "S2CRecvUnChatGroup",
	65780: "C2SChatGroupKick",
	65781: "MQChatGroupKick",
	65782: "S2CManagerKickSomeOne",
	65783: "S2CKickedByChatGroupManager",
	65784: "S2CRecvChatGroupKick",
	65790: "C2SChatGroupList",
	65791: "S2CChatGroupList",
	65800: "C2SGroupChat",
	65801: "S2CGroupChat",
	65802: "MQGroupChat",
	65803: "S2CRecvGroupChat",
	65804: "C2SChatGroupLastMsgTimeStamp",
	65810: "C2SGetOfflineGroupChatMsg",
	65811: "S2CGetOfflineGroupChatMsg",
	65820: "C2SWithdrawGroupMessage",
	65822: "S2CWithdrawGroupMessage",
	66000: "C2SFindUser",
	66001: "S2CFindUser",
	66010: "C2SAddFriendBlackList",
	66011: "S2CAddFriendBlackList",
	66020: "C2SMoveOutFriendBlackList",
	66021: "S2CMoveOutFriendBlackList",
	66030: "C2SGetFriendBlackList",
	66031: "S2CGetFriendBlackList",
	67000: "C2SSetWeiboCover",
	67001: "S2CSetWeiboCover",
	67010: "C2SLikeFriendWeiboCover",
	67011: "S2CLikeFriendWeiboCover",
	67012: "C2SGetWeiboCover",
	67013: "S2CGetWeiboCover",
	67020: "C2SPublishWeibo",
	67021: "MQPublishWeibo",
	67022: "S2CPublishWeibo",
	67023: "S2CRecvPublishWeibo",
	67030: "C2SLikeWeibo",
	67031: "MQLikeWeibo",
	67032: "S2CLikeWeibo",
	67033: "S2CRecvLikeWeibo",
	67040: "C2SCancelLikeWeibo",
	67041: "S2CCancelLikeWeibo",
	67050: "C2SReplyWeibo",
	67051: "MQReplyWeibo",
	67052: "S2CReplyWeibo",
	67053: "S2CRecvReplyWeibo",
	67060: "C2SDeleteReplyWeibo",
	67061: "S2CDeleteReplyWeibo",
	67070: "C2SDeleteWeibo",
	67071: "MQDeleteWeibo",
	67072: "S2CDeleteWeibo",
	67073: "S2CRecvDeleteWeibo",
	67080: "C2SBrowseSomeoneWeibo",
	67081: "S2CBrowseSomeoneWeibo",
	67100: "C2SBrowseAllWeibo",
	67101: "S2CBrowseAllWeibo",
	67110: "C2SDontLookFriendWeibo",
	67111: "S2CDontLookFriendWeibo",
	67120: "C2SForbiddenFriendLookWeibo",
	67121: "S2CForbiddenFriendLookWeibo",
	67130: "C2SAllowStrangerLookWeibo",
	67131: "S2CAllowStrangerLookWeibo",
	67140: "C2SFriendLookWeiboStrategy",
	67141: "S2CFriendLookWeiboStrategy",
	67150: "C2SGetDontLookFriendWeiboList",
	67151: "S2CGetDontLookFriendWeiboList",
	67160: "C2SGetForbiddenFriendLookWeiboList",
	67161: "S2CGetForbiddenFriendLookWeiboList",
	67170: "C2SIsAllowStrangerLookWeibo",
	67171: "S2CIsAllowStrangerLookWeibo",
	67180: "C2SGetFriendLookWeiboStrategy",
	67181: "S2CGetFriendLookWeiboStrategy",
	67132: "C2SSetFriendRemarkName",
	67133: "S2CSetFriendRemarkName",
	70000: "C2SHuanXinPush",
	70001: "S2CHuanXinPush",
	80000: "C2SThirdPlatformAccountLogin",
	80001: "S2CThirdPlatformAccountLogin",
}

var NetMsgId_value = map[string]int32{
	"msg_star_id":                                0,
	"C2l_gate_addr":                              60000,
	"L2c_gate_addr":                              60001,
	"S2CErrorCode":                               60002,
	"C2SRegisterAccount":                         65536,
	"S2CRegisterAccount":                         65537,
	"C2SLogin":                                   65538,
	"S2CLogin":                                   65539,
	"C2SCreateCharacter":                         65540,
	"S2CCreateCharacter":                         65541,
	"C2SLogout":                                  65542,
	"S2CLogout":                                  65543,
	"C2SHeartbeat":                               65544,
	"S2CHeartbeat":                               65545,
	"S2CKick":                                    65546,
	"S2CRepeatLogin":                             65547,
	"C2SRename":                                  65548,
	"S2CRename":                                  65549,
	"C2SDeviceInfo":                              65550,
	"S2CDeviceInfo":                              65551,
	"C2SSetUserName":                             65552,
	"S2CSetUserName":                             65553,
	"C2SSetHeadPortrait":                         65554,
	"S2CSetHeadPortrait":                         65555,
	"C2SChangePassword":                          65556,
	"S2CChangePassword":                          65557,
	"C2SForgetPassword":                          65558,
	"S2CForgetPassword":                          65559,
	"C2SGetVerificationCode":                     65560,
	"S2CGetVerificationCode":                     65561,
	"C2SUsernameLogin":                           65562,
	"S2CUsernameLogin":                           65563,
	"C2SLastMsgTimeStamp":                        65600,
	"C2SGetChatRecords":                          65602,
	"S2CGetChatRecords":                          65603,
	"C2SPrivateChat":                             65604,
	"MQPrivateChat":                              65607,
	"S2CPrivateChat":                             65605,
	"S2CRecvPrivateChat":                         65606,
	"S2COtherTerminalPrivateChat":                65613,
	"C2SGetOfflinePrivateChatMsg":                65608,
	"S2CGetOfflinePrivateChatMsg":                65609,
	"C2SPicWillBeSend":                           65610,
	"S2CPicWillBeSend":                           65611,
	"S2CLoginSomewhereElse":                      65612,
	"C2SWithdrawMessage":                         65614,
	"S2CWithdrawMessage":                         65616,
	"C2SAddFriend":                               65650,
	"MQAddFriend":                                65651,
	"S2CAddFriend":                               65652,
	"S2CRecvAddFriend":                           65653,
	"C2SAgreeBecomeFriend":                       65660,
	"MQAgreeBecomeFriend":                        65661,
	"S2CAgreeBecomeFriend":                       65662,
	"S2CRecvAgreeBecomeFriend":                   65663,
	"S2COtherTerminalAgreeBecomeFriend":          65664,
	"C2SReadFriendReq":                           65670,
	"S2CReadFriendReq":                           65672,
	"C2SDeleteFriend":                            65680,
	"MQDeleteFriend":                             65681,
	"S2CDeleteFriend":                            65682,
	"S2CRecvDeleteFriend":                        65683,
	"C2SConfirmDeleteFriend":                     65690,
	"S2CConfirmDeleteFriend":                     65691,
	"C2SCreateChatGroup":                         65700,
	"MQCreateChatGroup":                          65701,
	"S2CCreateChatGroup":                         65702,
	"S2CRecvCreateChatGroup":                     65703,
	"C2SReqJoinChatGroup":                        65710,
	"S2CRecvReqJoinChatGroup":                    65711,
	"MQReqJoinChatGroup":                         65712,
	"S2CSomeOneReqJoinChatGroup":                 65713,
	"C2SAgreeSomeOneReqJoinChatGroup":            65720,
	"MQAgreeSomeOneReqJoinChatGroup":             65721,
	"MQManagerAgreeSomeOneReqJoinChatGroup":      65722,
	"S2CManagerAgreeSomeOneReqJoinChatGroup":     65723,
	"S2CManagerAgreeJoinChatGroup":               65724,
	"S2CRecvManagerAgreeSomeOneReqJoinChatGroup": 65725,
	"C2SRefuseSomeOneReqJoinChatGroup":           65730,
	"MQRefuseSomeOneReqJoinChatGroup":            65731,
	"S2CManagerRefuseJoinChatGroup":              65732,
	"C2SChatGroupInfo":                           65740,
	"S2CChatGroupInfo":                           65741,
	"C2SInviteJoinChatGroup":                     65750,
	"MQInviteJoinChatGroup":                      65751,
	"S2CInviteYouJoinChatGroup":                  65752,
	"S2CRecvInviteJoinChatGroup":                 65753,
	"C2SCancelChatGroup":                         65760,
	"MQCancelChatGroup":                          65761,
	"S2CSomeOneCancelChatGroup":                  65762,
	"S2CRecvCancelChatGroup":                     65763,
	"C2SUnChatGroup":                             65770,
	"MQUnChatGroup":                              65771,
	"S2CUnChatGroup":                             65772,
	"S2CRecvUnChatGroup":                         65773,
	"C2SChatGroupKick":                           65780,
	"MQChatGroupKick":                            65781,
	"S2CManagerKickSomeOne":                      65782,
	"S2CKickedByChatGroupManager":                65783,
	"S2CRecvChatGroupKick":                       65784,
	"C2SChatGroupList":                           65790,
	"S2CChatGroupList":                           65791,
	"C2SGroupChat":                               65800,
	"S2CGroupChat":                               65801,
	"MQGroupChat":                                65802,
	"S2CRecvGroupChat":                           65803,
	"C2SChatGroupLastMsgTimeStamp":               65804,
	"C2SGetOfflineGroupChatMsg":                  65810,
	"S2CGetOfflineGroupChatMsg":                  65811,
	"C2SWithdrawGroupMessage":                    65820,
	"S2CWithdrawGroupMessage":                    65822,
	"C2SFindUser":                                66000,
	"S2CFindUser":                                66001,
	"C2SAddFriendBlackList":                      66010,
	"S2CAddFriendBlackList":                      66011,
	"C2SMoveOutFriendBlackList":                  66020,
	"S2CMoveOutFriendBlackList":                  66021,
	"C2SGetFriendBlackList":                      66030,
	"S2CGetFriendBlackList":                      66031,
	"C2SSetWeiboCover":                           67000,
	"S2CSetWeiboCover":                           67001,
	"C2SLikeFriendWeiboCover":                    67010,
	"S2CLikeFriendWeiboCover":                    67011,
	"C2SGetWeiboCover":                           67012,
	"S2CGetWeiboCover":                           67013,
	"C2SPublishWeibo":                            67020,
	"MQPublishWeibo":                             67021,
	"S2CPublishWeibo":                            67022,
	"S2CRecvPublishWeibo":                        67023,
	"C2SLikeWeibo":                               67030,
	"MQLikeWeibo":                                67031,
	"S2CLikeWeibo":                               67032,
	"S2CRecvLikeWeibo":                           67033,
	"C2SCancelLikeWeibo":                         67040,
	"S2CCancelLikeWeibo":                         67041,
	"C2SReplyWeibo":                              67050,
	"MQReplyWeibo":                               67051,
	"S2CReplyWeibo":                              67052,
	"S2CRecvReplyWeibo":                          67053,
	"C2SDeleteReplyWeibo":                        67060,
	"S2CDeleteReplyWeibo":                        67061,
	"C2SDeleteWeibo":                             67070,
	"MQDeleteWeibo":                              67071,
	"S2CDeleteWeibo":                             67072,
	"S2CRecvDeleteWeibo":                         67073,
	"C2SBrowseSomeoneWeibo":                      67080,
	"S2CBrowseSomeoneWeibo":                      67081,
	"C2SBrowseAllWeibo":                          67100,
	"S2CBrowseAllWeibo":                          67101,
	"C2SDontLookFriendWeibo":                     67110,
	"S2CDontLookFriendWeibo":                     67111,
	"C2SForbiddenFriendLookWeibo":                67120,
	"S2CForbiddenFriendLookWeibo":                67121,
	"C2SAllowStrangerLookWeibo":                  67130,
	"S2CAllowStrangerLookWeibo":                  67131,
	"C2SFriendLookWeiboStrategy":                 67140,
	"S2CFriendLookWeiboStrategy":                 67141,
	"C2SGetDontLookFriendWeiboList":              67150,
	"S2CGetDontLookFriendWeiboList":              67151,
	"C2SGetForbiddenFriendLookWeiboList":         67160,
	"S2CGetForbiddenFriendLookWeiboList":         67161,
	"C2SIsAllowStrangerLookWeibo":                67170,
	"S2CIsAllowStrangerLookWeibo":                67171,
	"C2SGetFriendLookWeiboStrategy":              67180,
	"S2CGetFriendLookWeiboStrategy":              67181,
	"C2SSetFriendRemarkName":                     67132,
	"S2CSetFriendRemarkName":                     67133,
	"C2SHuanXinPush":                             70000,
	"S2CHuanXinPush":                             70001,
	"C2SThirdPlatformAccountLogin":               80000,
	"S2CThirdPlatformAccountLogin":               80001,
}

func (x NetMsgId) String() string {
	return proto.EnumName(NetMsgId_name, int32(x))
}

func (NetMsgId) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_719e06d2e65a68c8, []int{0}
}

// 发朋友圈，朋友圈内容包含类型
type MsgWeibo int32

const (
	MsgWeibo_invalid_content MsgWeibo = 0
	// 仅文字
	MsgWeibo_text_only MsgWeibo = 1
	// 仅图片
	MsgWeibo_picture_only MsgWeibo = 2
	// 文字+图片
	MsgWeibo_text_picture MsgWeibo = 3
	// 仅视频
	MsgWeibo_radio_only MsgWeibo = 4
	// 文字+视频
	MsgWeibo_text_radio MsgWeibo = 5
)

var MsgWeibo_name = map[int32]string{
	0: "invalid_content",
	1: "text_only",
	2: "picture_only",
	3: "text_picture",
	4: "radio_only",
	5: "text_radio",
}

var MsgWeibo_value = map[string]int32{
	"invalid_content": 0,
	"text_only":       1,
	"picture_only":    2,
	"text_picture":    3,
	"radio_only":      4,
	"text_radio":      5,
}

func (x MsgWeibo) String() string {
	return proto.EnumName(MsgWeibo_name, int32(x))
}

func (MsgWeibo) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_719e06d2e65a68c8, []int{1}
}

// 朋友圈，操作类型
type MsgActionWeibo int32

const (
	// 发朋友圈
	MsgActionWeibo_publish_weibo MsgActionWeibo = 0
	// 删除朋友圈
	MsgActionWeibo_delete_weibo MsgActionWeibo = 1
	// 点赞朋友圈
	MsgActionWeibo_like_weibo MsgActionWeibo = 2
	// 取消点赞朋友圈
	MsgActionWeibo_cancel_like_weibo MsgActionWeibo = 3
	// 评论朋友圈
	MsgActionWeibo_comment_weibo MsgActionWeibo = 4
	// 删除朋友圈评论
	MsgActionWeibo_delete_comment_weibo MsgActionWeibo = 5
	// 设置看某好友朋友圈
	MsgActionWeibo_watch_someone_weibo MsgActionWeibo = 6
	// 设置不看某好友朋友圈
	MsgActionWeibo_not_watch_someone_weibo MsgActionWeibo = 7
	// 设置不允许某好友看自己朋友圈
	MsgActionWeibo_allow_someone_watch_weibo MsgActionWeibo = 8
	// 设置允许某好与看自己朋友圈
	MsgActionWeibo_not_allow_someone_watch_weibo MsgActionWeibo = 9
)

var MsgActionWeibo_name = map[int32]string{
	0: "publish_weibo",
	1: "delete_weibo",
	2: "like_weibo",
	3: "cancel_like_weibo",
	4: "comment_weibo",
	5: "delete_comment_weibo",
	6: "watch_someone_weibo",
	7: "not_watch_someone_weibo",
	8: "allow_someone_watch_weibo",
	9: "not_allow_someone_watch_weibo",
}

var MsgActionWeibo_value = map[string]int32{
	"publish_weibo":                 0,
	"delete_weibo":                  1,
	"like_weibo":                    2,
	"cancel_like_weibo":             3,
	"comment_weibo":                 4,
	"delete_comment_weibo":          5,
	"watch_someone_weibo":           6,
	"not_watch_someone_weibo":       7,
	"allow_someone_watch_weibo":     8,
	"not_allow_someone_watch_weibo": 9,
}

func (x MsgActionWeibo) String() string {
	return proto.EnumName(MsgActionWeibo_name, int32(x))
}

func (MsgActionWeibo) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_719e06d2e65a68c8, []int{2}
}

func init() {
	proto.RegisterEnum("msg_id.NetMsgId", NetMsgId_name, NetMsgId_value)
	proto.RegisterEnum("msg_id.MsgWeibo", MsgWeibo_name, MsgWeibo_value)
	proto.RegisterEnum("msg_id.MsgActionWeibo", MsgActionWeibo_name, MsgActionWeibo_value)
}

func init() { proto.RegisterFile("msg_id.proto", fileDescriptor_719e06d2e65a68c8) }

var fileDescriptor_719e06d2e65a68c8 = []byte{
	// 1928 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x58, 0xdb, 0x93, 0x15, 0x47,
	0x19, 0x67, 0xd9, 0x09, 0x81, 0x0e, 0x97, 0xa6, 0x81, 0x10, 0x42, 0xd8, 0x84, 0x98, 0x44, 0x0b,
	0x2d, 0xcb, 0x1a, 0xff, 0x82, 0xdd, 0x49, 0x58, 0xd0, 0x3d, 0x61, 0x77, 0x87, 0x88, 0x3e, 0x9d,
	0x9a, 0x9d, 0xe9, 0x3d, 0x67, 0x6a, 0xe7, 0x4c, 0x6f, 0x7a, 0xfa, 0xec, 0xca, 0xdb, 0xcc, 0x59,
	0x8d, 0x90, 0x19, 0x35, 0x01, 0x2f, 0x31, 0x89, 0x3e, 0xa4, 0x34, 0x79, 0xd3, 0xc4, 0xa7, 0x5c,
	0xab, 0x2c, 0x2e, 0x1a, 0x15, 0x08, 0x56, 0x51, 0x09, 0xe8, 0x0b, 0x2c, 0xfa, 0x92, 0x80, 0x8a,
	0x82, 0xfa, 0xa0, 0x60, 0x75, 0xf7, 0x74, 0x9f, 0x99, 0x39, 0xe7, 0x50, 0x3c, 0x9e, 0xdf, 0xef,
	0xd7, 0x5f, 0xf7, 0xf7, 0xf5, 0x77, 0xe9, 0x39, 0x60, 0x6d, 0x2b, 0x6a, 0xd4, 0x7d, 0xef, 0xf3,
	0xf3, 0x94, 0x30, 0x82, 0x56, 0xc9, 0x5f, 0xbb, 0x7e, 0xf9, 0x08, 0x58, 0xfd, 0x24, 0x66, 0xb5,
	0xa8, 0xb1, 0xd7, 0x43, 0x1b, 0xc0, 0x3d, 0x1c, 0x8e, 0x98, 0x43, 0xeb, 0xbe, 0x07, 0x57, 0xa0,
	0x4d, 0x60, 0x9d, 0x65, 0x06, 0xf5, 0x86, 0xc3, 0x70, 0xdd, 0xf1, 0x3c, 0x0a, 0x2f, 0x9e, 0x1b,
	0xe6, 0xe0, 0x84, 0xe9, 0x16, 0xc0, 0x4b, 0xe7, 0x86, 0x11, 0x02, 0x6b, 0x6d, 0xd3, 0x7a, 0x82,
	0x52, 0x42, 0x2d, 0xe2, 0x61, 0xb8, 0x7c, 0x6e, 0x18, 0xdd, 0x07, 0x90, 0x65, 0xda, 0xd3, 0xb8,
	0xe1, 0x47, 0x0c, 0xd3, 0x51, 0xd7, 0x25, 0xed, 0x90, 0xc1, 0x38, 0x36, 0x38, 0x63, 0x9b, 0x56,
	0x95, 0x49, 0x62, 0x03, 0xad, 0x07, 0xab, 0x2d, 0xd3, 0x9e, 0x20, 0x0d, 0x3f, 0x84, 0x1d, 0xf9,
	0xdb, 0x36, 0x2d, 0xf9, 0x7b, 0x49, 0xae, 0xb4, 0x4c, 0xdb, 0xa2, 0xd8, 0x61, 0xd8, 0x6a, 0x3a,
	0xd4, 0x71, 0x19, 0xa6, 0xf0, 0x1b, 0xda, 0x66, 0x95, 0xf9, 0x66, 0x6c, 0xa0, 0x0d, 0x60, 0x8d,
	0xb4, 0x49, 0xda, 0x0c, 0x3e, 0x23, 0x01, 0x69, 0x94, 0x03, 0xdf, 0x8a, 0x0d, 0x7e, 0x7a, 0xcb,
	0xb4, 0xf7, 0x60, 0x87, 0xb2, 0x19, 0xec, 0x30, 0x78, 0x48, 0x62, 0xb6, 0x69, 0x75, 0xb1, 0xc3,
	0xb1, 0x81, 0xd6, 0x81, 0xbb, 0x6d, 0xd3, 0xfa, 0xb2, 0xef, 0xce, 0xc1, 0x67, 0x63, 0x03, 0x6d,
	0x06, 0xeb, 0x85, 0x1b, 0xf3, 0xd8, 0x61, 0xf2, 0x88, 0xa9, 0xde, 0x6e, 0x1a, 0x87, 0x4e, 0x0b,
	0xc3, 0x4c, 0x6f, 0x97, 0x03, 0xdf, 0x8e, 0x0d, 0x19, 0x56, 0xfb, 0x71, 0xbc, 0xe0, 0xbb, 0x78,
	0x6f, 0x38, 0x4b, 0xe0, 0x77, 0x24, 0x68, 0x9b, 0x56, 0x01, 0xfc, 0xae, 0xdc, 0xc1, 0x32, 0x6d,
	0x1b, 0xb3, 0xa7, 0x22, 0x4c, 0x9f, 0xe4, 0xeb, 0x9f, 0xd3, 0xfb, 0x16, 0xd1, 0xe7, 0x75, 0x68,
	0x6c, 0xcc, 0xf6, 0x60, 0xc7, 0x9b, 0x24, 0x94, 0x51, 0xc7, 0x67, 0xf0, 0x88, 0x0e, 0x4d, 0x95,
	0x39, 0x1a, 0x1b, 0x68, 0x2b, 0xd8, 0xc8, 0xc3, 0xd9, 0x74, 0xc2, 0x06, 0x9e, 0x74, 0xa2, 0x68,
	0x91, 0x50, 0x0f, 0x7e, 0x4f, 0x12, 0x3c, 0x9a, 0x65, 0xe2, 0xfb, 0x7a, 0xc5, 0x6e, 0x42, 0x1b,
	0x98, 0x69, 0xe2, 0x07, 0x7a, 0x45, 0x85, 0xf8, 0x61, 0x6c, 0xa0, 0x07, 0xc0, 0xbd, 0x96, 0x69,
	0x8f, 0x63, 0xf6, 0x15, 0x4c, 0xfd, 0x59, 0xdf, 0x75, 0x98, 0x4f, 0x42, 0x91, 0x24, 0x2f, 0x48,
	0xd6, 0x36, 0xad, 0x7e, 0xec, 0x8f, 0x62, 0x03, 0xdd, 0x0b, 0xa0, 0x65, 0xda, 0xdc, 0x4d, 0x1e,
	0x3c, 0x19, 0xe3, 0x17, 0x25, 0x6e, 0x9b, 0x56, 0x19, 0x7f, 0x29, 0x36, 0xd0, 0x36, 0xb0, 0x89,
	0x5f, 0xb5, 0x13, 0xf1, 0x8c, 0xde, 0xef, 0xb7, 0xb0, 0xcd, 0x9c, 0xd6, 0x3c, 0xfc, 0x95, 0x3e,
	0xf8, 0x38, 0x66, 0x56, 0xd3, 0x61, 0xd3, 0xd8, 0x25, 0xd4, 0x8b, 0xe0, 0x31, 0x7d, 0xf0, 0x0a,
	0x71, 0x5c, 0x07, 0x7f, 0x92, 0xfa, 0x0b, 0x32, 0xa5, 0x18, 0x3c, 0x21, 0xef, 0xa9, 0x36, 0x55,
	0x04, 0x7f, 0xa3, 0x6f, 0xa4, 0x88, 0x9e, 0x2c, 0xa4, 0xb9, 0xbb, 0x50, 0x64, 0x7e, 0x1d, 0x1b,
	0x68, 0x27, 0xd8, 0x6e, 0x9b, 0xd6, 0x3e, 0xd6, 0xc4, 0x74, 0x3f, 0xa6, 0x2d, 0x3f, 0x74, 0x82,
	0xa2, 0xe4, 0xb4, 0x94, 0xc8, 0xf3, 0xee, 0x9b, 0x9d, 0x0d, 0xfc, 0x10, 0x17, 0xf8, 0x5a, 0xd4,
	0x80, 0xef, 0x6b, 0x2b, 0x03, 0x25, 0xbf, 0xd5, 0x01, 0x9c, 0xf4, 0xdd, 0x03, 0x7e, 0x10, 0x8c,
	0x61, 0x1b, 0x87, 0x1e, 0xfc, 0x9d, 0x0e, 0x60, 0x19, 0xff, 0x7d, 0x6c, 0xa0, 0xed, 0x60, 0x8b,
	0xaa, 0x37, 0x9b, 0xb4, 0xf0, 0x62, 0x13, 0x53, 0xfc, 0x44, 0x10, 0x61, 0x78, 0x4a, 0x67, 0xd8,
	0x01, 0x9f, 0x35, 0x3d, 0xea, 0x2c, 0xd6, 0x70, 0x14, 0x39, 0x0d, 0x0c, 0xcf, 0x68, 0x4f, 0xab,
	0xcc, 0x59, 0x5d, 0x5a, 0xa3, 0x9e, 0xb7, 0x9b, 0xfa, 0x7c, 0x93, 0x7f, 0xc4, 0x06, 0xda, 0x08,
	0xee, 0xa9, 0x4d, 0x75, 0xa1, 0x7f, 0xea, 0x6a, 0xeb, 0x62, 0xd7, 0xf5, 0x19, 0x79, 0xf8, 0xba,
	0xf8, 0x8d, 0xd8, 0x40, 0xf7, 0x83, 0xcd, 0xdc, 0x64, 0x83, 0x62, 0x3c, 0x86, 0x5d, 0xd2, 0xc2,
	0x39, 0xf7, 0x5f, 0x99, 0x00, 0xb5, 0xa9, 0x5e, 0xea, 0x7f, 0x72, 0x19, 0xdf, 0xa2, 0x87, 0xbb,
	0x19, 0x1b, 0x68, 0x04, 0xdc, 0xa7, 0xb6, 0xea, 0xe1, 0x6f, 0xc5, 0x06, 0xfa, 0x34, 0xd8, 0x59,
	0xbd, 0xaf, 0x5e, 0x61, 0x9c, 0xa8, 0x78, 0x4f, 0x63, 0x27, 0x3f, 0xf0, 0x34, 0x7e, 0x1a, 0x3e,
	0x93, 0x74, 0x7d, 0x29, 0xe2, 0x87, 0x12, 0x03, 0x6d, 0x01, 0x1b, 0x44, 0x2b, 0x08, 0x30, 0x53,
	0x66, 0x9e, 0x4b, 0x44, 0x3e, 0xd5, 0xa6, 0x4a, 0xe8, 0xf3, 0x52, 0x2c, 0x5a, 0x44, 0x01, 0x3e,
	0x92, 0x08, 0x9f, 0xf3, 0xc3, 0x97, 0xa8, 0xa3, 0x89, 0xaa, 0x3d, 0x8b, 0x84, 0xb3, 0x3e, 0x6d,
	0x95, 0xd8, 0x17, 0x13, 0x55, 0x7b, 0xfd, 0xd8, 0x97, 0x92, 0x9e, 0x56, 0xcb, 0xc6, 0x29, 0x69,
	0xcf, 0xc3, 0x9f, 0x26, 0xa2, 0x62, 0x6a, 0x53, 0x55, 0xe2, 0x67, 0x49, 0x4f, 0x0f, 0xce, 0x99,
	0x57, 0xf5, 0x56, 0xfc, 0x8c, 0x55, 0xf6, 0xb5, 0x44, 0x95, 0xed, 0x34, 0x7e, 0xfa, 0x4b, 0xc4,
	0x0f, 0xbb, 0xd4, 0xcf, 0x13, 0x03, 0xed, 0x00, 0x5b, 0xf3, 0x85, 0x3d, 0xf4, 0x2f, 0xe4, 0x8e,
	0xb5, 0xa9, 0x1e, 0xe6, 0xf5, 0xc4, 0x40, 0x0f, 0x81, 0xfb, 0x79, 0xd3, 0x23, 0x2d, 0xbc, 0x2f,
	0xc4, 0x3d, 0x8a, 0x37, 0x12, 0x03, 0x3d, 0x0a, 0x1e, 0x54, 0x79, 0x34, 0x48, 0xf6, 0x66, 0x62,
	0xa0, 0x47, 0xc0, 0x48, 0x9e, 0x52, 0x83, 0x54, 0x6f, 0x25, 0x06, 0xfa, 0x2c, 0x78, 0xb4, 0x36,
	0x55, 0x73, 0x42, 0xa7, 0x81, 0xe9, 0x6d, 0xc5, 0x6f, 0x27, 0x06, 0xfa, 0x1c, 0x78, 0xcc, 0x36,
	0xad, 0x3b, 0x51, 0xbf, 0x93, 0x18, 0xe8, 0x61, 0xf0, 0x40, 0x45, 0x5d, 0xd6, 0xbc, 0x9b, 0x18,
	0xe8, 0x0b, 0x60, 0x57, 0x1e, 0xa6, 0x3b, 0xb1, 0xfa, 0x5e, 0x62, 0xa0, 0xc7, 0xc0, 0x43, 0x22,
	0xe6, 0xb3, 0xed, 0x68, 0xa0, 0xee, 0x98, 0x8c, 0x12, 0x8f, 0xf0, 0xed, 0x64, 0xc7, 0x13, 0x03,
	0x7d, 0x0a, 0xec, 0xe8, 0x1e, 0x52, 0xca, 0xcb, 0xa2, 0x13, 0xba, 0x3a, 0x34, 0x26, 0xc6, 0xdc,
	0x29, 0x5d, 0x1d, 0x65, 0xfc, 0xb4, 0x4e, 0xdf, 0xbd, 0xe1, 0x82, 0xcf, 0x2a, 0xd6, 0x3e, 0x4c,
	0x44, 0xaf, 0xaa, 0x4d, 0xf5, 0x23, 0x3f, 0x4a, 0x0c, 0xf4, 0x20, 0xd8, 0x66, 0x9b, 0x96, 0x64,
	0xbf, 0x46, 0xda, 0x65, 0xc1, 0x79, 0x9d, 0x1f, 0x3c, 0x62, 0xfd, 0x4c, 0x5c, 0xe8, 0x16, 0x80,
	0x13, 0xba, 0x38, 0xe8, 0x32, 0x17, 0x75, 0x01, 0x54, 0x88, 0x4b, 0x7a, 0xd7, 0x3c, 0x4e, 0x55,
	0xc1, 0x72, 0xb9, 0x0e, 0x2a, 0xec, 0xe5, 0x44, 0x4d, 0x9c, 0xa7, 0x0a, 0xe7, 0xf8, 0x38, 0xc9,
	0x27, 0x4e, 0x11, 0xfc, 0x24, 0x51, 0x13, 0xa7, 0x88, 0x5e, 0x49, 0x8a, 0x13, 0xa7, 0xc8, 0x5c,
	0xed, 0x0d, 0xbd, 0x78, 0xc3, 0x5c, 0x97, 0x3d, 0xa5, 0x36, 0x55, 0x86, 0x6f, 0x24, 0x6a, 0x0e,
	0xe4, 0xd7, 0xc9, 0xd1, 0xdc, 0x27, 0xf8, 0xaf, 0x44, 0xcd, 0x1d, 0x8e, 0x62, 0x6f, 0xec, 0xa0,
	0x5e, 0x9c, 0xab, 0xe1, 0xbf, 0x13, 0xd5, 0x6c, 0x85, 0x9f, 0x25, 0xdb, 0xff, 0xe9, 0x3d, 0xca,
	0x84, 0x1f, 0x31, 0x78, 0xb3, 0x37, 0x0b, 0x04, 0x7e, 0x2b, 0x51, 0x23, 0x44, 0x60, 0x62, 0x3a,
	0x1e, 0xea, 0xa8, 0x79, 0xd1, 0xc5, 0x0e, 0x77, 0xf2, 0xb1, 0xd2, 0x85, 0x9e, 0xed, 0x14, 0x47,
	0x48, 0x17, 0x4f, 0x3b, 0xa2, 0xa4, 0x4a, 0x47, 0xa8, 0x3e, 0x18, 0xb2, 0x8e, 0xb8, 0xcb, 0xd2,
	0x00, 0xd6, 0x16, 0xf8, 0x6c, 0x3d, 0xd2, 0x51, 0x97, 0x3d, 0x40, 0x70, 0xb4, 0x23, 0x7a, 0x57,
	0x61, 0x5e, 0xca, 0x18, 0xe5, 0xa3, 0xf1, 0xe5, 0x8e, 0x6a, 0x6d, 0x7d, 0xe9, 0x9f, 0x48, 0x77,
	0xf8, 0x4b, 0xcb, 0x0f, 0x3d, 0xfe, 0xce, 0x81, 0x67, 0x97, 0x04, 0xc4, 0xdf, 0x58, 0x0a, 0xfa,
	0xc3, 0x92, 0xb8, 0xa8, 0xe2, 0x7c, 0x1d, 0x0b, 0x1c, 0x77, 0x4e, 0x44, 0xee, 0x8f, 0x4b, 0xea,
	0x16, 0xfb, 0x90, 0x7f, 0x5a, 0x52, 0xfe, 0xd5, 0xc8, 0x02, 0xde, 0xd7, 0x66, 0x55, 0xc1, 0x9f,
	0x97, 0x94, 0x7f, 0x03, 0x04, 0x7f, 0xd1, 0x7b, 0x8f, 0xe3, 0x1e, 0xf2, 0xaf, 0x7a, 0xef, 0x3e,
	0xe4, 0xdf, 0x96, 0x54, 0x0a, 0xd8, 0x98, 0x1d, 0xc0, 0xfe, 0x0c, 0xb1, 0xc8, 0x02, 0xa6, 0xf0,
	0xcd, 0x54, 0xdd, 0x57, 0x19, 0x7f, 0x2b, 0x55, 0x91, 0x9c, 0xf0, 0xe7, 0xf2, 0x01, 0x55, 0xa0,
	0x8f, 0xa5, 0x2a, 0x92, 0x7d, 0xe9, 0xe3, 0xa9, 0xda, 0x6d, 0xbc, 0x64, 0xf5, 0x84, 0xde, 0xad,
	0x8c, 0x9f, 0x4c, 0xd5, 0x50, 0x9e, 0x6c, 0xcf, 0x04, 0x7e, 0xd4, 0x14, 0x1c, 0x3c, 0x95, 0xe6,
	0x43, 0xb9, 0x84, 0x9e, 0x4e, 0xd5, 0x50, 0x2e, 0xc1, 0x67, 0xd2, 0xe2, 0x50, 0x2e, 0x51, 0x1f,
	0xa4, 0x2a, 0x9f, 0xf9, 0x69, 0x25, 0xf6, 0x61, 0x9a, 0xe7, 0x6e, 0x17, 0xfa, 0x28, 0x55, 0x29,
	0xde, 0xc5, 0xce, 0xa7, 0xc5, 0x7c, 0xee, 0xe2, 0x17, 0xd2, 0x72, 0xab, 0xea, 0x32, 0x17, 0x53,
	0x3d, 0x92, 0x2b, 0xcc, 0xa5, 0x54, 0x7d, 0x85, 0x4c, 0xe3, 0xf9, 0xe0, 0xa0, 0x04, 0x3f, 0x96,
	0x9b, 0xf2, 0x6e, 0xaf, 0xb1, 0x4f, 0x52, 0xf5, 0x65, 0x52, 0x00, 0xaf, 0xa4, 0xea, 0xd5, 0x2c,
	0xe7, 0xb2, 0x26, 0xae, 0xa6, 0x6a, 0x96, 0xcb, 0xd7, 0x44, 0x81, 0xba, 0xae, 0x63, 0xd2, 0x43,
	0xdd, 0x48, 0x55, 0xe7, 0x93, 0x94, 0x44, 0x6f, 0xa6, 0x79, 0xe7, 0x2b, 0x82, 0xb7, 0x52, 0xd5,
	0xf9, 0x8a, 0x68, 0x9c, 0x15, 0x3b, 0x5f, 0x91, 0x49, 0x32, 0x95, 0xa5, 0x63, 0x94, 0x2c, 0xca,
	0x09, 0x46, 0xc2, 0x9c, 0x3c, 0x94, 0xa9, 0x2c, 0xed, 0x43, 0x1e, 0xce, 0xd4, 0x27, 0x83, 0x24,
	0x47, 0x83, 0x40, 0x12, 0x2f, 0x67, 0xca, 0xf9, 0x0a, 0xf1, 0xe3, 0x4c, 0x0d, 0xac, 0xc7, 0x49,
	0xc8, 0x26, 0x08, 0x99, 0x2b, 0x24, 0x23, 0x7c, 0x35, 0x53, 0xcd, 0xbf, 0x1f, 0xfb, 0x5a, 0xa6,
	0x1e, 0xfc, 0xbb, 0x09, 0x9d, 0xf1, 0x3d, 0x0f, 0x87, 0x92, 0xe6, 0x42, 0x29, 0x79, 0x3d, 0x53,
	0x8d, 0x77, 0xa0, 0xe4, 0x8d, 0x4c, 0x55, 0xf5, 0x68, 0x10, 0x90, 0x45, 0x9b, 0x51, 0xfe, 0xf9,
	0x46, 0xbb, 0x82, 0xb7, 0x33, 0x55, 0xd5, 0x03, 0x04, 0xef, 0x64, 0x62, 0x30, 0xf2, 0x73, 0x94,
	0x6d, 0x73, 0x29, 0xc3, 0x8d, 0x83, 0xf0, 0x44, 0xa6, 0x46, 0xe7, 0x20, 0xc5, 0xc9, 0x4c, 0xbc,
	0x06, 0x64, 0xc5, 0xf5, 0x71, 0x56, 0x34, 0x81, 0x33, 0x99, 0x7a, 0x32, 0xdc, 0x46, 0xf4, 0x41,
	0x66, 0xa0, 0xcf, 0x80, 0x87, 0xf3, 0x1e, 0x33, 0xc0, 0x6b, 0xa1, 0x3c, 0x2f, 0x95, 0x79, 0xc3,
	0xb9, 0x9d, 0xf2, 0x82, 0x8e, 0xf4, 0xde, 0x68, 0x40, 0x10, 0x96, 0x75, 0xa4, 0x07, 0x4a, 0x2e,
	0x17, 0x7d, 0x1c, 0x14, 0x88, 0x2b, 0x45, 0x1f, 0x07, 0x89, 0xae, 0xea, 0xac, 0xb1, 0x95, 0x68,
	0x1a, 0xb7, 0x1c, 0x3a, 0x27, 0xbe, 0xeb, 0xdf, 0xd5, 0x59, 0xd3, 0x8f, 0x7d, 0x2f, 0x53, 0x85,
	0xb3, 0xa7, 0xed, 0x84, 0x5f, 0xf5, 0xc3, 0xc9, 0x76, 0xd4, 0x84, 0x7f, 0x7f, 0x45, 0xd5, 0x48,
	0x11, 0xbd, 0xf6, 0x8a, 0x9a, 0x7a, 0xfb, 0x9b, 0x3e, 0xf5, 0x26, 0x03, 0x87, 0xcd, 0x12, 0xda,
	0xca, 0xff, 0x7b, 0x91, 0x5f, 0xd0, 0xf1, 0x35, 0xf5, 0xd8, 0x1c, 0xac, 0x49, 0xae, 0x19, 0xbb,
	0x28, 0x58, 0x5d, 0x8b, 0x1a, 0xc2, 0x0f, 0xb4, 0x09, 0x6c, 0xf0, 0xc3, 0x05, 0x27, 0xf0, 0xbd,
	0xba, 0x4b, 0x42, 0x86, 0x43, 0x06, 0x57, 0xa0, 0x75, 0x60, 0x0d, 0xc3, 0x5f, 0x67, 0x75, 0x12,
	0x06, 0x07, 0xe1, 0x10, 0x82, 0x60, 0xed, 0xbc, 0xef, 0xb2, 0x36, 0xc5, 0x12, 0x59, 0xc9, 0x11,
	0x21, 0xc8, 0x61, 0x38, 0x8c, 0xd6, 0x03, 0x40, 0x1d, 0xcf, 0x27, 0x52, 0x61, 0xf0, 0xdf, 0x42,
	0x21, 0x40, 0x78, 0xd7, 0xae, 0x64, 0x25, 0x58, 0x5f, 0x8b, 0x1a, 0xa3, 0x2e, 0xf3, 0x49, 0x28,
	0xb7, 0xde, 0x08, 0xd6, 0xcd, 0xcb, 0xde, 0x5a, 0x5f, 0x14, 0xb7, 0xb2, 0x82, 0xdb, 0xf5, 0x44,
	0xf9, 0xe7, 0xc8, 0x10, 0xb7, 0x13, 0xf8, 0x73, 0xea, 0xf7, 0x4a, 0xb4, 0x05, 0x6c, 0x74, 0x45,
	0x33, 0xac, 0x17, 0xe0, 0x61, 0x6e, 0xcb, 0x25, 0xad, 0x16, 0x0e, 0x59, 0x0e, 0xf1, 0x8e, 0xb2,
	0x39, 0xb7, 0x55, 0x66, 0xee, 0x42, 0x5b, 0xc1, 0xa6, 0x45, 0x87, 0xb9, 0xcd, 0x7a, 0x24, 0x3b,
	0x46, 0x4e, 0xac, 0x42, 0xdb, 0xc1, 0xd6, 0x90, 0xb0, 0x7a, 0x3f, 0xf2, 0x6e, 0xb4, 0x03, 0x6c,
	0x73, 0x78, 0x36, 0x75, 0x09, 0x21, 0x93, 0xf4, 0x6a, 0xb4, 0x13, 0xec, 0xe0, 0x6b, 0x07, 0x4b,
	0xd6, 0x8c, 0xc1, 0xf7, 0x97, 0x47, 0x86, 0xce, 0x2e, 0x8f, 0x0c, 0x5d, 0x5c, 0x1e, 0x19, 0x7a,
	0xe1, 0xf2, 0xc8, 0x8a, 0x99, 0x55, 0xe2, 0xdf, 0xbc, 0x2f, 0xfe, 0x3f, 0x00, 0x00, 0xff, 0xff,
	0x3f, 0x8f, 0x20, 0x15, 0xdd, 0x13, 0x00, 0x00,
}
